CONTRIBUTING.md

remove OCA

---

CONTRIBUTING.md

Fix broken metadata link

---

.github/workflows/test-all-metadata.yml
.github/workflows/test-changed-metadata.yml
gradle/checkstyle.xml
tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/TestLookupLogic.groovy

This PR relaxes checkstyle rules and improves GitHub Actions output.

Relax checkstyle rules

---

metadata/org.quartz-scheduler/quartz/2.3.2/index.json
metadata/org.quartz-scheduler/quartz/2.3.2/reflect-config.json
metadata/org.quartz-scheduler/quartz/2.3.2/serialization-config.json
tests/src/org.quartz-scheduler/quartz/2.3.2/build.gradle
tests/src/org.quartz-scheduler/quartz/2.3.2/src/test/java/org/quartz/QuartzTest.java
tests/src/org.quartz-scheduler/quartz/2.3.2/src/test/java/org/quartz/SimpleJob.java

Refine Quartz metadata for Spring use case and the tests.

Quartz refinements

---

metadata/com.sun.mail/jakarta.mail/2.0.1/index.json
metadata/com.sun.mail/jakarta.mail/2.0.1/reflect-config.json
metadata/com.sun.mail/jakarta.mail/2.0.1/resource-config.json
metadata/com.sun.mail/jakarta.mail/index.json
metadata/index.json
tests/src/com.sun.mail/jakarta.mail/2.0.1/build.gradle
tests/src/com.sun.mail/jakarta.mail/2.0.1/gradle.properties
tests/src/com.sun.mail/jakarta.mail/2.0.1/settings.gradle
tests/src/com.sun.mail/jakarta.mail/2.0.1/src/test/java/com/sun/mail/JakartaMailTest.java
tests/src/index.json

Focused on SMTP for now.
Closes gh-18

Add jakarta.mail metadata

---

metadata/index.json
metadata/io.netty/netty-common/index.json
metadata/io.netty/netty-transport/index.json
metadata/org.example/library/index.json
tests/src/io.netty/netty-common/4.1.80.Final/build.gradle
tests/src/org.example/library/0.0.1/gradle.properties
tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck.gradle
tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/tasks/AbstractSubprojectTask.groovy

Adds TCK support for the `override` flag

Add TCK support for the `override` flag

---

build.gradle

Release `0.2.0` version of GraalVM Reachability Metadata repository

Release `0.2.0`

---

build.gradle

Bumps the repository version to `0.2.1-SNAPSHOT`

Bump the repository version to `0.2.1-SNAPSHOT`

---

metadata/index.json
metadata/org.glassfish.jaxb/jaxb-runtime/3.0.2/index.json
metadata/org.glassfish.jaxb/jaxb-runtime/3.0.2/reflect-config.json
metadata/org.glassfish.jaxb/jaxb-runtime/index.json
tests/src/index.json
tests/src/org.glassfish.jaxb/jaxb-runtime/3.0.2/build.gradle
tests/src/org.glassfish.jaxb/jaxb-runtime/3.0.2/gradle.properties
tests/src/org.glassfish.jaxb/jaxb-runtime/3.0.2/settings.gradle
tests/src/org.glassfish.jaxb/jaxb-runtime/3.0.2/src/test/java/org/glassfish/jaxb/Foo.java
tests/src/org.glassfish.jaxb/jaxb-runtime/3.0.2/src/test/java/org/glassfish/jaxb/JaxbTest.java

Add Glassfish JAXB metadata

---

metadata/ch.qos.logback/logback-classic/1.4.1/index.json
metadata/ch.qos.logback/logback-classic/1.4.1/reflect-config.json
metadata/ch.qos.logback/logback-classic/1.4.1/resource-config.json
metadata/ch.qos.logback/logback-classic/index.json
tests/src/ch.qos.logback/logback-classic/1.4.1/build.gradle
tests/src/ch.qos.logback/logback-classic/1.4.1/gradle.properties
tests/src/ch.qos.logback/logback-classic/1.4.1/settings.gradle
tests/src/ch.qos.logback/logback-classic/1.4.1/src/test/java/org/graalvm/logback/LogbackTests.java
tests/src/ch.qos.logback/logback-classic/1.4.1/user-code-filter.json
tests/src/index.json

It adds support for Logback 1.4, see also #62 related issue.

Add Logback 1.4 metadata

---

metadata/index.json
metadata/org.thymeleaf/thymeleaf-spring6/3.1.0.M2/index.json
metadata/org.thymeleaf/thymeleaf-spring6/3.1.0.M2/reflect-config.json
metadata/org.thymeleaf/thymeleaf-spring6/index.json
metadata/org.thymeleaf/thymeleaf/3.1.0.M2/index.json
metadata/org.thymeleaf/thymeleaf/3.1.0.M2/reflect-config.json
metadata/org.thymeleaf/thymeleaf/3.1.0.M2/resource-config.json
metadata/org.thymeleaf/thymeleaf/index.json
tests/src/index.json
tests/src/org.thymeleaf/thymeleaf-spring6/3.1.0.M2/build.gradle
tests/src/org.thymeleaf/thymeleaf-spring6/3.1.0.M2/gradle.properties
tests/src/org.thymeleaf/thymeleaf-spring6/3.1.0.M2/settings.gradle
tests/src/org.thymeleaf/thymeleaf-spring6/3.1.0.M2/src/test/java/org/thymeleaf/ThymeleafSpring6Test.java
tests/src/org.thymeleaf/thymeleaf-spring6/3.1.0.M2/user-code-filter.json
tests/src/org.thymeleaf/thymeleaf/3.1.0.M2/build.gradle
tests/src/org.thymeleaf/thymeleaf/3.1.0.M2/gradle.properties
tests/src/org.thymeleaf/thymeleaf/3.1.0.M2/settings.gradle
tests/src/org.thymeleaf/thymeleaf/3.1.0.M2/src/test/java/org/thymeleaf/ThymeleafExtraTest.java
tests/src/org.thymeleaf/thymeleaf/3.1.0.M2/src/test/java/org/thymeleaf/ThymeleafTest.java
tests/src/org.thymeleaf/thymeleaf/3.1.0.M2/user-code-filter.json
tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle

Closes gh-21
It adds support for Thymeleaf 3.1.0.M2.

Add Thymeleaf metadata

---

metadata/index.json
metadata/org.freemarker/freemarker/2.3.31/index.json
metadata/org.freemarker/freemarker/2.3.31/resource-config.json
metadata/org.freemarker/freemarker/index.json
tests/src/index.json
tests/src/org.freemarker/freemarker/2.3.31/build.gradle
tests/src/org.freemarker/freemarker/2.3.31/gradle.properties
tests/src/org.freemarker/freemarker/2.3.31/settings.gradle
tests/src/org.freemarker/freemarker/2.3.31/src/test/java/fm/FreemarkerTest.java
tests/src/org.freemarker/freemarker/2.3.31/src/test/java/fm/Product.java
tests/src/org.freemarker/freemarker/2.3.31/src/test/resources/META-INF/native-image/reflect-config.json
tests/src/org.freemarker/freemarker/2.3.31/src/test/resources/META-INF/native-image/resource-config.json
tests/src/org.freemarker/freemarker/2.3.31/src/test/resources/test.ftlh
tests/src/org.freemarker/freemarker/2.3.31/user-code-filter.json

Closes gh-38
This PR adds support for Freemarker.

Add Freemarker metadata

---

metadata/com.ecwid.consul/consul-api/1.4.5/index.json
metadata/com.ecwid.consul/consul-api/1.4.5/reflect-config.json
metadata/com.ecwid.consul/consul-api/1.4.5/resource-config.json
metadata/com.ecwid.consul/consul-api/index.json
metadata/index.json
tests/src/com.ecwid.consul/consul-api/1.4.5/.gitignore
tests/src/com.ecwid.consul/consul-api/1.4.5/build.gradle
tests/src/com.ecwid.consul/consul-api/1.4.5/gradle.properties
tests/src/com.ecwid.consul/consul-api/1.4.5/settings.gradle
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/java/com/ecwid/consul/AclConsulClientTests.java
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/java/com/ecwid/consul/CatalogConsulClientTests.java
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/java/com/ecwid/consul/CoordinateConsulClientTests.java
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/java/com/ecwid/consul/EventConsulClientTests.java
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/java/com/ecwid/consul/HealthConsulClientTests.java
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/java/com/ecwid/consul/KeyValueConsulClientTests.java
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/java/com/ecwid/consul/QueryConsulClientTests.java
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/java/com/ecwid/consul/QueryParamsTest.java
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/java/com/ecwid/consul/SessionConsulClientTests.java
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/java/com/ecwid/consul/StatusConsulClientTests.java
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/java/com/ecwid/consul/utils/ConsulTestUtils.java
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/resources/META-INF/native-image/commons-logging-hints/reflect-config.json
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/resources/META-INF/native-image/tomcat-hints/reflect-config.json
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/resources/META-INF/native-image/tomcat-hints/resource-config.json
tests/src/com.ecwid.consul/consul-api/1.4.5/src/test/resources/commons-logging.properties
tests/src/com.ecwid.consul/consul-api/README.md
tests/src/index.json

Add Consul API 1.4.5 metadata

---

gradle/libs.versions.toml
tests/src/com.ecwid.consul/consul-api/README.md
tests/src/org.hibernate.validator/hibernate-validator/README.md

Update NBT to 0.9.14

---

metadata/index.json
metadata/org.eclipse.jetty/jetty-server/11.0.12/index.json
metadata/org.eclipse.jetty/jetty-server/11.0.12/reflect-config.json
metadata/org.eclipse.jetty/jetty-server/11.0.12/resource-config.json
metadata/org.eclipse.jetty/jetty-server/index.json
tests/src/index.json
tests/src/org.eclipse.jetty/jetty-server/11.0.12/.gitignore
tests/src/org.eclipse.jetty/jetty-server/11.0.12/build.gradle
tests/src/org.eclipse.jetty/jetty-server/11.0.12/gradle.properties
tests/src/org.eclipse.jetty/jetty-server/11.0.12/settings.gradle
tests/src/org.eclipse.jetty/jetty-server/11.0.12/src/test/java/jetty/HelloWorldServlet.java
tests/src/org.eclipse.jetty/jetty-server/11.0.12/src/test/java/jetty/JakartaWebSocketServerEndpoint.java
tests/src/org.eclipse.jetty/jetty-server/11.0.12/src/test/java/jetty/JettyTests.java
tests/src/org.eclipse.jetty/jetty-server/11.0.12/src/test/java/jetty/WebSocketClientEndpoint.java
tests/src/org.eclipse.jetty/jetty-server/11.0.12/src/test/java/jetty/WebSocketServerEndpoint.java
tests/src/org.eclipse.jetty/jetty-server/11.0.12/src/test/resources/META-INF/native-image/test/reflect-config.json
tests/src/org.eclipse.jetty/jetty-server/11.0.12/user-code-filter.json

Rebased version of https://github.com/oracle/graalvm-reachability-metadata/pull/78.

Add metadata for org.eclipse.jetty 11.0.12 (rebased)

---

metadata/com.mysql/mysql-connector-j/8.0.31/index.json
metadata/com.mysql/mysql-connector-j/8.0.31/reflect-config.json
metadata/com.mysql/mysql-connector-j/8.0.31/resource-config.json
metadata/com.mysql/mysql-connector-j/index.json
metadata/index.json
tests/src/com.mysql/mysql-connector-j/8.0.31/.gitignore
tests/src/com.mysql/mysql-connector-j/8.0.31/build.gradle
tests/src/com.mysql/mysql-connector-j/8.0.31/gradle.properties
tests/src/com.mysql/mysql-connector-j/8.0.31/settings.gradle
tests/src/com.mysql/mysql-connector-j/8.0.31/src/test/java/mysql/MySQLTests.java
tests/src/index.json

Adds metadata for `com.mysql:mysql-connector-j:8.0.3`
Closes #86

Add metadata for com.mysql:mysql-connector-j

---

metadata/org.thymeleaf/thymeleaf/3.1.0.RC1/index.json
metadata/org.thymeleaf/thymeleaf/3.1.0.RC1/reflect-config.json
metadata/org.thymeleaf/thymeleaf/3.1.0.RC1/resource-config.json
metadata/org.thymeleaf/thymeleaf/index.json
tests/src/index.json
tests/src/org.thymeleaf/thymeleaf/3.1.0.RC1/build.gradle
tests/src/org.thymeleaf/thymeleaf/3.1.0.RC1/gradle.properties
tests/src/org.thymeleaf/thymeleaf/3.1.0.RC1/settings.gradle
tests/src/org.thymeleaf/thymeleaf/3.1.0.RC1/src/test/java/org/thymeleaf/ThymeleafTest.java
tests/src/org.thymeleaf/thymeleaf/3.1.0.RC1/user-code-filter.json

Fix a package/dependency change for `Temporals` class.

Add metadata for thymeleaf 3.1.0.RC1

---

gradle/libs.versions.toml

Update NBT to 0.9.16

---

metadata/index.json
metadata/org.liquibase/liquibase-core/4.17.0/index.json
metadata/org.liquibase/liquibase-core/4.17.0/reflect-config.json
metadata/org.liquibase/liquibase-core/4.17.0/resource-config.json
metadata/org.liquibase/liquibase-core/index.json
tests/src/index.json
tests/src/org.liquibase/liquibase-core/4.17.0/.gitignore
tests/src/org.liquibase/liquibase-core/4.17.0/build.gradle
tests/src/org.liquibase/liquibase-core/4.17.0/gradle.properties
tests/src/org.liquibase/liquibase-core/4.17.0/settings.gradle
tests/src/org.liquibase/liquibase-core/4.17.0/src/test/java/org_liquibase/liquibase_core/LiquibaseCoreTest.java
tests/src/org.liquibase/liquibase-core/4.17.0/src/test/resources/META-INF/native-image/test/resource-config.json
tests/src/org.liquibase/liquibase-core/4.17.0/src/test/resources/changelog.yaml
tests/src/org.liquibase/liquibase-core/4.17.0/user-code-filter.json

Adds metadata for liquibase.
Closes #27.

Add metadata for Liquibase

---

.github/workflows/library-and-framework-list-validation.yml
.github/workflows/test-all-metadata.yml
.github/workflows/test-changed-metadata.yml
.gitmodules
CONTRIBUTING.md
tests/tck-build-logic/build.gradle
tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/Coordinates.java
tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/ScaffoldTask.java
tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/model/MetadataIndexEntry.java
tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/model/TestIndexEntry.java
tests/tck-build-logic/src/main/resources/scaffold/.gitignore.template
tests/tck-build-logic/src/main/resources/scaffold/Test.java.template
tests/tck-build-logic/src/main/resources/scaffold/build.gradle.template
tests/tck-build-logic/src/main/resources/scaffold/gradle.properties.template
tests/tck-build-logic/src/main/resources/scaffold/metadataIndex.json.template
tests/tck-build-logic/src/main/resources/scaffold/metadataVersionIndex.json.template
tests/tck-build-logic/src/main/resources/scaffold/serialization-config.json.template
tests/tck-build-logic/src/main/resources/scaffold/settings.gradle.template
tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/CoordinatesTests.java
tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/model/MetadataIndexEntryTests.java
tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/model/TestIndexEntryTests.java

Adds a task to create metadata and tests.
Run with `gradle scaffold --coordinates com.example:my-library:1.0.0`.
Closes #88.

Add 'scaffold' task to generate metadata and tests for a library

---

library-and-framework-list-schema.json

Make minimum and maximum version consistent.

---

metadata/index.json
metadata/org.jboss.logging/jboss-logging/3.5.0.Final/index.json
metadata/org.jboss.logging/jboss-logging/3.5.0.Final/reflect-config.json
metadata/org.jboss.logging/jboss-logging/index.json
tests/src/index.json
tests/src/org.jboss.logging/jboss-logging/3.5.0.Final/.gitignore
tests/src/org.jboss.logging/jboss-logging/3.5.0.Final/build.gradle
tests/src/org.jboss.logging/jboss-logging/3.5.0.Final/gradle.properties
tests/src/org.jboss.logging/jboss-logging/3.5.0.Final/settings.gradle
tests/src/org.jboss.logging/jboss-logging/3.5.0.Final/src/test/java/org_jboss_logging/jboss_logging/Jboss_loggingTest.java
tests/src/org.jboss.logging/jboss-logging/3.5.0.Final/src/test/resources/META-INF/native-image/test/reflect-config.json
tests/src/org.jboss.logging/jboss-logging/3.5.0.Final/user-code-filter.json

Adds metadata for `jboss-logging`.
Closes #110

Add metadata for jboss-logging

---

tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-base.gradle
tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck.gradle

Fix "Could not get unknown property 'metadataRoot' for root project"

---

library-and-framework-list-schema.json
library-and-framework-list.json

Provide a first list of supported libraries and make `tests-locations` optional.

Provide a first list of supported libraries 

---

library-and-framework-list.json

Mark `io.netty:netty5-parent` as `community-tested`.

---

CONTRIBUTING.md
README.md

Add Library and Framework List Contributing Paragraph

Add Library and Framework List Contributing Paragraph

---

metadata/index.json
metadata/org.eclipse.jetty/jetty-client/11.0.12/index.json
metadata/org.eclipse.jetty/jetty-client/11.0.12/reflect-config.json
metadata/org.eclipse.jetty/jetty-client/11.0.12/resource-config.json
metadata/org.eclipse.jetty/jetty-client/index.json
tests/src/index.json
tests/src/org.eclipse.jetty/jetty-client/11.0.12/.gitignore
tests/src/org.eclipse.jetty/jetty-client/11.0.12/README.md
tests/src/org.eclipse.jetty/jetty-client/11.0.12/build.gradle
tests/src/org.eclipse.jetty/jetty-client/11.0.12/gradle.properties
tests/src/org.eclipse.jetty/jetty-client/11.0.12/settings.gradle
tests/src/org.eclipse.jetty/jetty-client/11.0.12/src/test/java/org_eclipse_jetty/jetty_client/JettyClientTest.java
tests/src/org.eclipse.jetty/jetty-client/11.0.12/user-code-filter.json

Adds metadata for Jetty client.

Add metadata for jetty-client

---

tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck.gradle

- Fixes https://github.com/oracle/graalvm-reachability-metadata/issues/126 .

Raise the project's Java language level to 17

---

library-and-framework-list.json

Add ojdbc8 and ojdbc11 to the native-image support list

Add ojdbc8 and ojdbc11 to the native-image support list

---

metadata/com.sun.mail/jakarta.mail/2.0.1/reflect-config.json
metadata/org.eclipse.angus/jakarta.mail/1.0.0/reflect-config.json
tests/src/com.sun.mail/jakarta.mail/2.0.1/src/test/java/com/sun/mail/JakartaMailTest.java
tests/src/org.eclipse.angus/jakarta.mail/1.0.0/src/test/java/com/sun/mail/JakartaMailTest.java

It adds multipart support to Jakarta mail.

Add multipart support to Jakarta mail

---

metadata/index.json
metadata/org.opengauss/opengauss-jdbc/3.1.0-og/index.json
metadata/org.opengauss/opengauss-jdbc/3.1.0-og/reflect-config.json
metadata/org.opengauss/opengauss-jdbc/3.1.0-og/resource-config.json
metadata/org.opengauss/opengauss-jdbc/index.json
tests/src/index.json
tests/src/org.opengauss/opengauss-jdbc/3.1.0-og/.gitignore
tests/src/org.opengauss/opengauss-jdbc/3.1.0-og/build.gradle
tests/src/org.opengauss/opengauss-jdbc/3.1.0-og/gradle.properties
tests/src/org.opengauss/opengauss-jdbc/3.1.0-og/settings.gradle
tests/src/org.opengauss/opengauss-jdbc/3.1.0-og/src/test/java/org_opengauss/opengauss_jdbc/Opengauss_jdbcTest.java

- Fixes https://github.com/oracle/graalvm-reachability-metadata/issues/166.

Add support for `org.opengauss:opengauss-jdbc:3.1.0-og`

---

.github/workflows/all-checks.yml
.github/workflows/check-all-metadata-jobs.yml

Creates job that waits other actions to pass. This job should be required as it summarize outputs of all other jobs

Add job that waits all actions to pass

---

library-and-framework-list.json

Adds Micronaut to libraries and frameworks list

Add Micronaut

---

.github/workflows/library-and-framework-list-validation.yml
CONTRIBUTING.md
library-and-framework-list.json

Validate and sort `library-and-framework-list.json` with `jq` (instead of `./gradlew :spotlessApply`).

Sort `library-and-framework-list.json`

---

tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/TckExtension.java

Checks if newly added metadata contains corresponding entry in `metadata/index.json` file.

Catch missing metadata entry in index.json file

---

.github/workflows/checkstyle.yml
.github/workflows/library-and-framework-list-validation.yml
.github/workflows/test-all-metadata.yml
.github/workflows/test-changed-metadata.yml

- Fixes https://github.com/oracle/graalvm-reachability-metadata/issues/226 .

Restrict Github Actions Jobs from being executed on Forked branches

---

CONTRIBUTING.md

This PR polishes the `CONTRIBUTING.md` file a bit.

Polish CONTRIBUTING.md

---

tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle

Re-enable dev build testing against JDK17.

---

metadata/org.liquibase/liquibase-core/4.17.0/reflect-config.json
tests/src/org.liquibase/liquibase-core/4.17.0/src/test/java/org_liquibase/liquibase_core/LiquibaseCoreTest.java

Fixes https://github.com/oracle/graalvm-reachability-metadata/issues/244

Fix the second launch of Liquibase

---

gradle/libs.versions.toml

- Fixes https://github.com/oracle/graalvm-reachability-metadata/issues/175 .

Update the project's Junit and GraalVM Native Build Tools versions

---

tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/tasks/TestInvocationTask.groovy

This PR allows overriding the toolchain search path for tests (kudos to @melix for coming up and writing this approach! :))
- [ X] I have properly formatted metadata files (see [CONTRIBUTING](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md) document)
- [X ] I have added thorough tests. (see [this](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))

Allow overriding the test toolchain search path

---

build.gradle

Add missing Snapshot to version

Bump to snapshot

---

tests/src/org.eclipse.jetty/jetty-client/11.0.12/.gitignore
tests/src/org.eclipse.jetty/jetty-client/11.0.12/required-docker-images.txt
tests/src/org.eclipse.jetty/jetty-client/11.0.12/src/test/java/org_eclipse_jetty/jetty_client/JettyClientTest.java

Refactor jetty client test to use nginx in docker as http backend

---

README.md

It adds a link to the ["Ready for Native Image" web page](https://www.graalvm.org/native-image/libraries-and-frameworks/) and additional information to the `README.md`.

Improve and extend `README.md`.

---

tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/ScaffoldTask.java
tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/model/MetadataIndexEntry.java

Extends scaffold task with newly added entry `allowed-packages`

Add allowed-packages to scaffold task

---

CONTRIBUTING.md
README.md
pull_request_template.md

Extends Readme file with the explanation of how to test your project or local changes of this repo, locally.

Add explanation how to use metadata repository locally

---

build.gradle

Create release 0.3.2

---

build.gradle

Bumps repo version to 0.3.3-SNAPSHOT

Bump repo version to 0.3.3-SNAPSHOT

---

metadata/org.liquibase/liquibase-core/4.17.0/reflect-config.json
metadata/org.liquibase/liquibase-core/4.20.0/reflect-config.json
tests/src/org.liquibase/liquibase-core/4.17.0/src/test/java/org_liquibase/liquibase_core/LiquibaseCoreTest.java
tests/src/org.liquibase/liquibase-core/4.17.0/src/test/resources/changelog.xml

Adds additional liquibase metadata

Liquibase additional metadata

---

.github/workflows/test-changed-metadata-skip.yml

Adds another missing but required job to skip workflow. Following up on #336 and #339

Add missing required job to skip workflow.

---

library-and-framework-list.json

remove duplicate entry for micronaut-test-bom

---

CONTRIBUTING.md
REVIEWING.md
pull_request_template.md

Adds reviewing guide and extends pull request checklist

Add Reviewing Guide

---

library-and-framework-list.json

Add information about com.github.ladutsko:isbn-core to library-and-framework-list.json

Add information about com.github.ladutsko:isbn-core to library-and-framework-list.json

---

.github/workflows/checkstyle-skip.yml
.github/workflows/checkstyle.yml
.github/workflows/library-and-framework-list-validation-skip.yml
.github/workflows/library-and-framework-list-validation.yml
.github/workflows/scan-docker-images-skip.yml
.github/workflows/scan-docker-images.yml

We currently run a couple of workflows multiple times. Only run some on `pull_request` to avoid needless duplication.

Run some workflows on `pull_request` only.

---

.github/workflows/test-all-metadata.yml
.github/workflows/test-changed-metadata.yml
tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck.gradle

Enables dev builds in github actions

Enable dev builds in github actions

---

tests/src/org.apache.httpcomponents/httpclient/4.5.14/.gitignore
tests/src/org.apache.httpcomponents/httpclient/4.5.14/build.gradle
tests/src/org.apache.httpcomponents/httpclient/4.5.14/src/test/java/org_apache_httpcomponents/httpclient/HttpClientTest.java

Trying to troubleshooting occasional http client connection issues

Http client connection issue

---

build.gradle

Create release 0.3.3

---

build.gradle

Bumps repo version to 0.3.4-SNAPSHOT

Bump repo version to 0.3.4-SNAPSHOT

---

build.gradle

Bump repo version to 0.3.4

---

metadata/org.liquibase/liquibase-core/4.23.0/index.json
metadata/org.liquibase/liquibase-core/4.23.0/reflect-config.json
metadata/org.liquibase/liquibase-core/4.23.0/resource-config.json
metadata/org.liquibase/liquibase-core/index.json
tests/src/index.json

Adds metadata for org.liquibase:liquibase-core:4.23.0

Added metadata for org.liquibase:liquibase-core:4.23.0

---

metadata/ch.qos.logback.contrib/logback-jackson/0.1.5/index.json
metadata/ch.qos.logback.contrib/logback-jackson/0.1.5/reflect-config.json
metadata/ch.qos.logback.contrib/logback-jackson/index.json
metadata/ch.qos.logback.contrib/logback-json-classic/0.1.5/index.json
metadata/ch.qos.logback.contrib/logback-json-classic/0.1.5/reflect-config.json
metadata/ch.qos.logback.contrib/logback-json-classic/index.json
metadata/index.json
tests/src/ch.qos.logback.contrib/logback-jackson/0.1.5/.gitignore
tests/src/ch.qos.logback.contrib/logback-jackson/0.1.5/build.gradle
tests/src/ch.qos.logback.contrib/logback-jackson/0.1.5/gradle.properties
tests/src/ch.qos.logback.contrib/logback-jackson/0.1.5/settings.gradle
tests/src/ch.qos.logback.contrib/logback-jackson/0.1.5/src/test/java/ch_qos_logback_contrib/logback_jackson/LogbackJacksonTest.java
tests/src/ch.qos.logback.contrib/logback-jackson/0.1.5/src/test/resources/META-INF/native-image/logback-contrib-tests-only/reflect-config.json
tests/src/ch.qos.logback.contrib/logback-json-classic/0.1.5/.gitignore
tests/src/ch.qos.logback.contrib/logback-json-classic/0.1.5/build.gradle
tests/src/ch.qos.logback.contrib/logback-json-classic/0.1.5/gradle.properties
tests/src/ch.qos.logback.contrib/logback-json-classic/0.1.5/settings.gradle
tests/src/ch.qos.logback.contrib/logback-json-classic/0.1.5/src/test/java/ch_qos_logback_contrib/logback_json_classic/CustomJsonFormatter.java
tests/src/ch.qos.logback.contrib/logback-json-classic/0.1.5/src/test/java/ch_qos_logback_contrib/logback_json_classic/LogbackJsonClassicTest.java
tests/src/ch.qos.logback.contrib/logback-json-classic/0.1.5/src/test/resources/META-INF/native-image/logback-contrib-tests-only/reflect-config.json
tests/src/index.json

Added metadata for:
- ch.qos.logback.contrib:logback-jackson:0.1.5
- ch.qos.logback.contrib:logback-json-classic:0.1.5

Logback json metadata

---

metadata/index.json
tests/src/index.json
tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/ScaffoldTask.java

Sorts entries by `module` in metadata index.json file and by `test-project-path` in tests index.json file. Each time when the Scaffold task is executed, entries will be sorted in those files. These changes reduce PR merge conflicts.

Sorted entries in metadata and tests index.json files

---

.github/CODEOWNERS

Adds default reviewers for docker images and library and framework list

Extend CODEOWNERS file

---

.github/workflows/scan-docker-images-skip.yml
.github/workflows/scan-docker-images.yml

Fix workflow paths for scan docker images action

---

build.gradle

Bumps repository version to 0.3.6

Prepare Repository for Release 0.3.6

---

metadata/index.json
metadata/org.bouncycastle/bcpkix-jdk15to18/1.77/index.json
metadata/org.bouncycastle/bcpkix-jdk15to18/1.77/reflect-config.json
metadata/org.bouncycastle/bcpkix-jdk15to18/index.json
tests/src/index.json
tests/src/org.bouncycastle/bcpkix-jdk15to18/1.77/.gitignore
tests/src/org.bouncycastle/bcpkix-jdk15to18/1.77/build.gradle
tests/src/org.bouncycastle/bcpkix-jdk15to18/1.77/gradle.properties
tests/src/org.bouncycastle/bcpkix-jdk15to18/1.77/metadata-extra-filter.json
tests/src/org.bouncycastle/bcpkix-jdk15to18/1.77/metadata-user-code-filter.json
tests/src/org.bouncycastle/bcpkix-jdk15to18/1.77/settings.gradle
tests/src/org.bouncycastle/bcpkix-jdk15to18/1.77/src/test/java/org_bouncycastle/bcpkix_jdk15to18/BouncyCastleTest.java

Adds metadata for org.bouncycastle:bcpkix-jdk15to18:1.77

Added metadata for org.bouncycastle:bcpkix-jdk15to18:1.77

---

tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle

I realized this is not needed and there's another way to do what we need.

Revert "Add ability to ignore matrix defaults."

---

tests/src/org.thymeleaf.extras/thymeleaf-extras-springsecurity6/3.1.0.M1/build.gradle

Context: https://github.com/spring-projects/spring-framework/issues/32444#issuecomment-2009387273

Avoid Spring milestones in `org.thymeleaf.extras` test.

---

.github/workflows/checkstyle.yml
.github/workflows/library-and-framework-list-validation.yml
.github/workflows/scan-docker-images.yml
.github/workflows/test-all-metadata.yml
.github/workflows/test-changed-metadata.yml
tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com/google/protobuf/util/DurationsTest.java
tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com/google/protobuf/util/FieldMaskTreeTest.java
tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com/google/protobuf/util/JsonFormatTest.java
tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com/google/protobuf/util/TimestampsTest.java
tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com_google_protobuf/protobuf_java_util/FieldMaskUtilTest.java
tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com_google_protobuf/protobuf_java_util/StructsTest.java
tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com_google_protobuf/protobuf_java_util/ValuesTest.java
tests/src/io.undertow/undertow-core/2.2.19.Final/build.gradle
tests/src/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/build.gradle
tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/TckExtension.java

- Runs ci actions with `latest-ea` builds
- Fixes kotlin, undertow and protobuf tests to pass on `latest-ea`
- Updates `actions/checkout` and `actions/setup-java` versions

Run latest ea builds in GitHub actions

---

build.gradle

Prepares repository for the next release

Bump repo version

---

build.gradle

Bump repo version to next SNAPSHOT

---

tests/src/org.eclipse.paho/org.eclipse.paho.client.mqttv3/1.2.5/required-docker-images.txt
tests/src/org.eclipse.paho/org.eclipse.paho.client.mqttv3/1.2.5/src/test/java/org_eclipse_paho/org_eclipse_paho_client_mqttv3/Mqttv3Test.java
tests/src/org.eclipse.paho/org.eclipse.paho.mqttv5.client/1.2.5/required-docker-images.txt
tests/src/org.eclipse.paho/org.eclipse.paho.mqttv5.client/1.2.5/src/test/java/org_eclipse_paho/org_eclipse_paho_mqttv5_client/Mqttv5ClientTest.java
tests/tck-build-logic/src/main/resources/allowed-docker-images/Dockerfile-eclipse-mosquitto

Update eclipse-mosquitto docker image from version `2.0.15` to version `2.0.18`

Update eclipse-mosquitto docker image

---

metadata/index.json
metadata/org.hibernate/hibernate-spatial/6.5.0.Final/index.json
metadata/org.hibernate/hibernate-spatial/6.5.0.Final/reflect-config.json
metadata/org.hibernate/hibernate-spatial/index.json
tests/src/index.json
tests/src/org.hibernate/hibernate-spatial/6.5.0.Final/.gitignore
tests/src/org.hibernate/hibernate-spatial/6.5.0.Final/build.gradle
tests/src/org.hibernate/hibernate-spatial/6.5.0.Final/gradle.properties
tests/src/org.hibernate/hibernate-spatial/6.5.0.Final/settings.gradle
tests/src/org.hibernate/hibernate-spatial/6.5.0.Final/src/test/java/org_hibernate/hibernate_spatial/HibernateSpatialTest.java

Add support for Hibernate Spatial

---

metadata/org.postgresql/postgresql/42.7.3/index.json
metadata/org.postgresql/postgresql/42.7.3/reflect-config.json
metadata/org.postgresql/postgresql/index.json
tests/src/index.json
tests/src/org.postgresql/postgresql/42.7.3/.gitignore
tests/src/org.postgresql/postgresql/42.7.3/build.gradle
tests/src/org.postgresql/postgresql/42.7.3/gradle.properties
tests/src/org.postgresql/postgresql/42.7.3/required-docker-images.txt
tests/src/org.postgresql/postgresql/42.7.3/settings.gradle
tests/src/org.postgresql/postgresql/42.7.3/src/test/java/postgresql/PostgresqlTests.java

added tests for PostgreSQL JDBC version 42.7.3
- [x ] I have filled all places where my pull request accesses files, network, docker, or any other external service (see the section above)

add metadata and tests for PostgreSQL JDBC version 42.7.3

---

build.gradle

Prepares repository for a new release

Bump repo version to 0.3.9

---

metadata/io.netty/netty-common/4.1.115.Final/reflect-config.json
tests/src/io.netty/netty-common/4.1.115.Final/src/test/java/netty/NettyTests.java

Update Netty 4.1.115.Final metadata
n/a

Update Netty 4.1.115.Final metadata

---

.github/workflows/check-new-library-versions.yml
.github/workflows/checkstyle.yml
.github/workflows/create-scheduled-release.yml
.github/workflows/library-and-framework-list-validation.yml
.github/workflows/scan-docker-images.yml
.github/workflows/test-all-metadata.yml
.github/workflows/test-changed-metadata.yml
tests/src/org.apache.kafka/kafka-clients/3.5.1/src/test/java/org_apache_kafka/kafka_clients/KafkaClientsTest.java

This PR updates Ubuntu version used in github actions from 20.04 to 22.04

Update ubuntu version used in github actions

---

CONTRIBUTING.md
metadata/org.apache.tomcat.embed/tomcat-embed-core/10.0.20/reflect-config.json
metadata/org.hibernate.orm/hibernate-core/7.0.0.Final/reflect-config.json
metadata/org.testcontainers/testcontainers/1.17.6/reflect-config.json
tests/tck-build-logic/src/main/resources/contributing/questions.json

Fixes: https://github.com/oracle/graal/actions/runs/17464628128

Fixes for --future-defaults=all in GraalVM 25
