oracle/graalvm-reachability-metadata

- build.gradle
This PR makes sure that `gradle package` outputs versioned zip to the build directory.
Fixes #3
> Output versioned zip in `package` task

- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck.gradle
Signed-off-by: Moritz Halbritter <mkammerer@vmware.com>
Sets the Java language level to 11 to catch language bugs locally.
> Set Java language level to 11

- metadata/index.json
- metadata/org.hibernate.validator/hibernate-validator/7.0.4.Final/index.json
- metadata/org.hibernate.validator/hibernate-validator/7.0.4.Final/proxy-config.json
- metadata/org.hibernate.validator/hibernate-validator/7.0.4.Final/reflect-config.json
- metadata/org.hibernate.validator/hibernate-validator/7.0.4.Final/resource-config.json
- metadata/org.hibernate.validator/hibernate-validator/index.json
- tests/src/index.json
- tests/src/org.hibernate.validator/hibernate-validator/7.0.4.Final/build.gradle
- tests/src/org.hibernate.validator/hibernate-validator/7.0.4.Final/gradle.properties
- tests/src/org.hibernate.validator/hibernate-validator/7.0.4.Final/settings.gradle
- tests/src/org.hibernate.validator/hibernate-validator/7.0.4.Final/src/test/java/org/hibernate/validator/Dto.java
- tests/src/org.hibernate.validator/hibernate-validator/7.0.4.Final/src/test/java/org/hibernate/validator/HibernateValidatorTest.java
- tests/src/org.hibernate.validator/hibernate-validator/7.0.4.Final/src/test/resources/META-INF/native-image/dto-hints/reflect-config.json
- tests/src/org.hibernate.validator/hibernate-validator/README.md
Signed-off-by: Moritz Halbritter <mkammerer@vmware.com>
Adds metadata for hibernate validator. The readme in the tests explains how these files have been generated.
> Add config for hibernate-validator

- metadata/index.json
- metadata/org.jetbrains.kotlin/kotlin-reflect/1.7.10/index.json
- metadata/org.jetbrains.kotlin/kotlin-reflect/1.7.10/reflect-config.json
- metadata/org.jetbrains.kotlin/kotlin-reflect/1.7.10/resource-config.json
- metadata/org.jetbrains.kotlin/kotlin-reflect/index.json
- tests/src/index.json
- tests/src/org.jetbrains.kotlin/kotlin-reflect/1.7.10/build.gradle
- tests/src/org.jetbrains.kotlin/kotlin-reflect/1.7.10/gradle.properties
- tests/src/org.jetbrains.kotlin/kotlin-reflect/1.7.10/settings.gradle
- tests/src/org.jetbrains.kotlin/kotlin-reflect/1.7.10/src/test/kotlin/kotlinreflect/KotlinReflectTests.kt
- tests/src/org.jetbrains.kotlin/kotlin-reflect/1.7.10/src/test/resources/META-INF/native-image/test/reflect-config.json
- tests/src/org.jetbrains.kotlin/kotlin-reflect/1.7.10/user-code-filter.json
Closes gh-20
Signed-off-by: Moritz Halbritter <mkammerer@vmware.com>
Adds metadata for kotlin-reflect.
> Add metadata for kotlin-reflect

- metadata/index.json
- metadata/org.quartz-scheduler/quartz/2.3.2/index.json
- metadata/org.quartz-scheduler/quartz/2.3.2/reflect-config.json
- metadata/org.quartz-scheduler/quartz/2.3.2/resource-config.json
- metadata/org.quartz-scheduler/quartz/index.json
- tests/src/index.json
- tests/src/org.quartz-scheduler/quartz/2.3.2/build.gradle
- tests/src/org.quartz-scheduler/quartz/2.3.2/gradle.properties
- tests/src/org.quartz-scheduler/quartz/2.3.2/settings.gradle
- tests/src/org.quartz-scheduler/quartz/2.3.2/src/test/java/org/quartz/QuartzTest.java
> Add initial quartz metadata

- metadata/com.h2database/h2/2.1.210/index.json
- metadata/com.h2database/h2/2.1.210/reflect-config.json
- metadata/com.h2database/h2/2.1.210/resource-config.json
- tests/src/com.h2database/h2/2.1.210/build.gradle
- tests/src/com.h2database/h2/2.1.210/user-code-filter.json
The existing metadata was referencing types which no longer exist in H2.
The new metadata has been generated by running the tests with the agent attached.
For example a h2 running in a native image using the old metadata was unable to write files to disk. `h2:mem:...` works without problems, but `h2:file:...` would not write any file.
I tried reproducing that behaviour in a test, but you have to shut down the whole JVM to observe it.
> Fix H2 metadata

- metadata/io.netty/netty-common/4.1.80.Final/reflect-config.json
- tests/src/io.netty/netty-common/4.1.80.Final/build.gradle
This PR adds missing metadata for different `ChannelHandler` implementations in Netty 4.1.80.
We also no longer need a snapshot repo for Netty 4.1.80 as this version has been officially released
> Add Netty 4 ChannelHandler metadata

- metadata/ch.qos.logback/logback-classic/1.2.11/reflect-config.json
- tests/src/ch.qos.logback/logback-classic/1.2.11/src/test/java/org/graalvm/logback/LogbackTests.java
This is often used for SLF4J detection.
See #41 for details.
Closes #41
Adds `org.slf4j.impl.StaticLoggerBinder` to logback reflection hints.
> Make sure that org.slf4j.impl.StaticLoggerBinder is available

- tests/src/org.example/library/0.0.1/build.gradle
- tests/src/org.example/library/0.0.1/gradle.properties
- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck.gradle
- Bumps `setup-graalvm` action to the current master
- Fixes error that gets thrown when running tests from the test directory which is missing `library.override` and `library.coordinates`
- Removes redundant stuff from the test template (`org.example:library`)
> TCK improvements

- metadata/io.netty/netty-transport/index.json
- tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/MetadataLookupLogic.groovy
It reverts 40992cc18a69da5f395788a9ac56987ba5ad1c30 and update `netty-transport` metadata to provide 2 distinct entries for `4.1.76.Final` and `4.1.80.Final`.
> Metadata version fix

- README.md
I've noticed that the existing link (https://www.graalvm.org/22.2/reference-manual/native-image/ReachabilityMetadata/) returns 404, this fixed it. i also dropped the version number from the URL, this way the link will always redirect to the latest docs.
> fix the link to metadata docs

- metadata/org.hibernate.orm/hibernate-core/6.1.1.Final/reflect-config.json
- tests/src/org.hibernate.orm/hibernate-core/6.1.1.Final/src/test/java/org/hibernate/orm/Cart.java
- tests/src/org.hibernate.orm/hibernate-core/6.1.1.Final/src/test/java/org/hibernate/orm/HibernateOrmTest.java
- tests/src/org.hibernate.orm/hibernate-core/6.1.1.Final/src/test/java/org/hibernate/orm/Item.java
- tests/src/org.hibernate.orm/hibernate-core/6.1.1.Final/src/test/resources/META-INF/native-image/dto-runtime-hints/reflect-config.json
- tests/src/org.hibernate.orm/hibernate-core/README.md
Add missing hibernate-orm metadata extracted from the `org.hibernate.orm:hibernate-graalvm` artifact. This allows users to operate without having to add the extra dependency.
> Add missing hints extracted from org.hibernate.orm:hibernate-graalvm:6.1.1.Final

- metadata/org.hibernate.orm/hibernate-core/6.1.1.Final/reflect-config.json
- tests/src/org.hibernate.orm/hibernate-core/6.1.1.Final/src/test/java/org/hibernate/orm/HibernateOrmTest.java
- tests/src/org.hibernate.orm/hibernate-core/6.1.1.Final/src/test/java/org/hibernate/orm/User.java
- tests/src/org.hibernate.orm/hibernate-core/6.1.1.Final/src/test/resources/META-INF/native-image/dto-runtime-hints/reflect-config.json
- tests/src/org.hibernate.orm/hibernate-core/README.md
Add missing hints for types potentially instantiated via `StandardIdentifierGeneratorFactory` and update test to make use of the now added generator.
Hints have been extracted by running test located in the `id` package of `hibernate-core` with the agent attached, filtering on `org.hibernate.id`. Since not all types used in `StandardIdentifierGeneratorFactory` got recorded, missing entries (like the ones for `SelectGenerator`) were added manually.
> Add missing hibernate-orm hints for id generation.

- metadata/org.hibernate.orm/hibernate-core/6.1.1.Final/reflect-config.json
Provide reflection metadata for hibernate orm dialects:
- postgresql
- mariadb
- mysql
- cockroachdb
- hsqldb
- oracle
- sqlserver
Run tests located in `hibernate-core` package `dialect` against the defined target database with the agent attached filtering on types of the corresponding drivers/dialects. Additionally diff the things and add only non existing ones.
> Add hints for additional hibernate-orm dialects

- metadata/index.json
- metadata/io.undertow/undertow-core/2.2.19.Final/index.json
- metadata/io.undertow/undertow-core/2.2.19.Final/reflect-config.json
- metadata/io.undertow/undertow-core/2.2.19.Final/resource-config.json
- metadata/io.undertow/undertow-core/index.json
- tests/src/index.json
- tests/src/io.undertow/undertow-core/2.2.19.Final/.gitignore
- tests/src/io.undertow/undertow-core/2.2.19.Final/build.gradle
- tests/src/io.undertow/undertow-core/2.2.19.Final/gradle.properties
- tests/src/io.undertow/undertow-core/2.2.19.Final/settings.gradle
- tests/src/io.undertow/undertow-core/2.2.19.Final/src/test/java/undertow/MessageServlet.java
- tests/src/io.undertow/undertow-core/2.2.19.Final/src/test/java/undertow/UndertowTests.java
- tests/src/io.undertow/undertow-core/2.2.19.Final/src/test/java/undertow/WebSocketHandler.java
- tests/src/io.undertow/undertow-core/2.2.19.Final/src/test/resources/META-INF/native-image/test/reflect-config.json
- tests/src/io.undertow/undertow-core/2.2.19.Final/user-code-filter.json
Adds metadata for undertow. It supports `undertow-core`, `undertow-servlet`, `undertow-websockets` and `undertow-websockets-jsr`.
Closes #75
> Metadata for undertow

- metadata/index.json
- metadata/org.thymeleaf.extras/thymeleaf-extras-springsecurity6/3.1.0.M1/index.json
- metadata/org.thymeleaf.extras/thymeleaf-extras-springsecurity6/3.1.0.M1/reflect-config.json
- metadata/org.thymeleaf.extras/thymeleaf-extras-springsecurity6/index.json
- tests/src/index.json
- tests/src/org.thymeleaf.extras/thymeleaf-extras-springsecurity6/3.1.0.M1/build.gradle
- tests/src/org.thymeleaf.extras/thymeleaf-extras-springsecurity6/3.1.0.M1/gradle.properties
- tests/src/org.thymeleaf.extras/thymeleaf-extras-springsecurity6/3.1.0.M1/settings.gradle
- tests/src/org.thymeleaf.extras/thymeleaf-extras-springsecurity6/3.1.0.M1/src/test/java/org/thymeleaf/extras/ThymeleafSpringSecurityTest.java
It adds support for `org.thymeleaf.extras:thymeleaf-extras-springsecurity6`.
> Add thymeleaf-extras-springsecurity6 metadata

- metadata/org.hibernate.validator/hibernate-validator/7.0.4.Final/reflect-config.json
- tests/src/org.hibernate.validator/hibernate-validator/7.0.4.Final/build.gradle
- tests/src/org.hibernate.validator/hibernate-validator/7.0.4.Final/src/main/java/org/hibernate/validator/FindValidators.java
- tests/src/org.hibernate.validator/hibernate-validator/7.0.4.Final/src/main/resources/template.txt
- tests/src/org.hibernate.validator/hibernate-validator/7.0.4.Final/src/test/java/org/hibernate/validator/Dto.java
- tests/src/org.hibernate.validator/hibernate-validator/7.0.4.Final/src/test/java/org/hibernate/validator/HibernateValidatorTest.java
- tests/src/org.hibernate.validator/hibernate-validator/README.md
I've added all of the validator implementations into the `reflect-config.json` file.
I auto-generated the JSON snippets with `FindValidators`, which is included in the PR.
> Add all hibernate validator implementations to reflect-config.json

- metadata/org.hibernate.orm/hibernate-core/6.1.1.Final/reflect-config.json
- tests/src/org.hibernate.orm/hibernate-core/6.1.1.Final/src/test/java/org/hibernate/orm/HibernateOrmTest.java
This PR adds hints for types created reflectively via `org.hibernate.cfg.annotations.PropertyBinder` based on types provided via (meta) annotation attributes via commit 0.
Additionally commit 1 updates the reflection config to reduce build time warnings due to invalid configuration which will close #107 .
> Update hibernate-orm hints to cover AttributeBinder & ValueGenerationTypes

- metadata/io.netty/netty-common/4.1.80.Final/jni-config.json
- metadata/io.netty/netty-common/4.1.80.Final/reflect-config.json
- metadata/io.netty/netty-common/4.1.80.Final/resource-config.json
Netty provides MacOS specific nameserver resolution - `resolver-dns-classes-macos` and `resolver-dns-native-macos`.
The PR adds metadata for Netty MacOS specific nameserver resolution.
The exception below is observed when there is no metadata for this functionality:
```
java.lang.NoSuchMethodException: io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.<init>()
at java.base@19.0.1/java.lang.Class.getConstructor0(DynamicHub.java:3641) ~[client:na]
at java.base@19.0.1/java.lang.Class.getConstructor(DynamicHub.java:2324) ~[client:na]
at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:63) ~[na:na]
at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:60) ~[na:na]
```
Closes #100
Test is not provided …
> Add metadata for Netty MacOS specific nameserver resolution

- metadata/io.netty/netty-common/4.1.80.Final/reflect-config.json
Apache Log4j2 does not work in a native image and that will be the case [until Log4j2 3.0 at the earliest](https://issues.apache.org/jira/browse/LOG4J2-2649). Furthermore, Netty's `InternalLoggerFactory` is written such that SLF4J is preferred. As such, it does not make sense for Netty to provide reflection metadata for Log4j2 – in must cases the code that tries to use Log4j2 won't be reached and when it is, Log4j2 will not be usable anyway.
In addition to the reflection metadata for Log4j2 not being beneficial to Netty, it's also harmful when using JBoss Logging. The metadata is sufficient for JBoss Logging's attempt to use Log4j2 to reach the point where error-level logging of stack traces is performed before falling back to another logging framework. Without Netty's metadata for …
> Remove Log4j2 entries from netty-common's reflection metadata

- metadata/org.eclipse.angus/jakarta.mail/1.0.0/index.json
- metadata/org.eclipse.angus/jakarta.mail/1.0.0/reflect-config.json
- metadata/org.eclipse.angus/jakarta.mail/1.0.0/resource-config.json
- metadata/org.eclipse.angus/jakarta.mail/index.json
- tests/src/index.json
- tests/src/org.eclipse.angus/jakarta.mail/1.0.0/build.gradle
- tests/src/org.eclipse.angus/jakarta.mail/1.0.0/gradle.properties
- tests/src/org.eclipse.angus/jakarta.mail/1.0.0/settings.gradle
- tests/src/org.eclipse.angus/jakarta.mail/1.0.0/src/test/java/com/sun/mail/JakartaMailTest.java
As part of Jakarta EE 10, the coordinates of the Jakarta Mail reference implementation have been updated with the group ID changing from `com.sun.mail` to `org.eclipse.angus`. This makes the existing metadata for `com.sun.mail:jakarta.mail` ineffective.
This PR adds metadata for the the new artifact, focusing on SMTP as the [existing metadata](https://github.com/oracle/graalvm-reachability-metadata/pull/44) does.
> Add metadata for Eclipse Angus Jakarta Mail reference implementation

- metadata/org.hibernate.orm/hibernate-core/6.1.1.Final/reflect-config.json
Hibernate's metadata contains entries for various MBean-related classes. This metadata causes a call to
`ManagementFactory.getPlatformMBeanServer()` to [fail with a `javax.management.openmbean.OpenDataException`](https://github.com/spring-projects/spring-boot/issues/33210). It would appear that the metadata is sufficient for the bootstrapping of the MBean server to take a different code path to normal and this path fails. This PR removes the offending metadata which fixes `ManagementFactory.getPlatformMBeanServer()` and has no adverse effects on the existing tests for hibernate-core.
No new tests have been added but the existing tests are unaffected by the changes.
> Remove MBean-related entries from hibernate-core's metadata

- .github/workflows/test-all-metadata.yml
- .github/workflows/test-changed-metadata.yml
Enable the new `native-image-job-reports` and `native-image-pr-reports` options, which post Native Image build reports as job summaries and as comments on pull requests (see https://github.com/graalvm/setup-graalvm/pull/20).
n/a
> Enable Native Image build reports for build jobs and PRs

- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
Upgrades the GraalVM version used to run the tests to `22.3.0`. This should fix the build jobs that have the new Native Image build reports enabled.
n/a
> Upgrade to GraalVM `22.3.0`.

- metadata/index.json
- metadata/org.hibernate.orm/hibernate-envers/6.1.1.Final/index.json
- metadata/org.hibernate.orm/hibernate-envers/6.1.1.Final/proxy-config.json
- metadata/org.hibernate.orm/hibernate-envers/6.1.1.Final/reflect-config.json
- metadata/org.hibernate.orm/hibernate-envers/6.1.1.Final/resource-config.json
- metadata/org.hibernate.orm/hibernate-envers/index.json
- tests/src/index.json
- tests/src/org.hibernate.orm/hibernate-envers/6.1.1.Final/build.gradle
- tests/src/org.hibernate.orm/hibernate-envers/6.1.1.Final/gradle.properties
- tests/src/org.hibernate.orm/hibernate-envers/6.1.1.Final/settings.gradle
- tests/src/org.hibernate.orm/hibernate-envers/6.1.1.Final/src/test/java/org/hibernate/envers/Event.java
- tests/src/org.hibernate.orm/hibernate-envers/6.1.1.Final/src/test/java/org/hibernate/envers/HibernateOrmTest.java
- tests/src/org.hibernate.orm/hibernate-envers/6.1.1.Final/src/test/java/org/hibernate/envers/Target_Environment.java
- tests/src/org.hibernate.orm/hibernate-envers/6.1.1.Final/src/test/resources/META-INF/native-image/dto-runtime-hints/reflect-config.json
- tests/src/org.hibernate.orm/hibernate-envers/6.1.1.Final/src/test/resources/META-INF/native-image/dto-runtime-hints/resource-config.json
- tests/src/org.hibernate.orm/hibernate-envers/README.md
This PR provides an initial set of hints extracted from running integration tests of `hibernate-envers` with the agent attached as well a set of manually added ones that turned out to be missing when testing the generated metadata.
Any hibernate-envers features that requires runtime hint proxy creation will not work.
Closes: #82
> Add initial set of hints for hibernate-envers

- .github/workflows/library-and-framework-list-validation.yml
- .github/workflows/test-all-metadata.yml
- .github/workflows/test-changed-metadata.yml
This PR adds reasonable timeouts (5m and 20min) to all build jobs to cancel stale builds as early as possible (the default timeout is 6h, which is way too much). [Here's an example build job](https://github.com/oracle/graalvm-reachability-metadata/actions/runs/3621925163) that failed after 6 hours.
Related to https://github.com/oracle/graalvm-reachability-metadata/pull/122#issuecomment-1338515655.
n/a
> Add `timeout-minutes` to all build jobs.

- library-and-framework-list.json
Add a few of Helidon libraries that support native image.
```
graalvm-reachability-metadata/tests/src/ch.qos.logback/logback-classic/1.2.11"): error=2, No such file or directory
```
> Core Helidon Libraries

- metadata/index.json
- metadata/org.mockito/mockito-core/4.8.1/index.json
- metadata/org.mockito/mockito-core/4.8.1/reflect-config.json
- metadata/org.mockito/mockito-core/4.8.1/resource-config.json
- metadata/org.mockito/mockito-core/index.json
- tests/src/index.json
- tests/src/org.mockito/mockito-core/4.8.1/.gitignore
- tests/src/org.mockito/mockito-core/4.8.1/README.md
- tests/src/org.mockito/mockito-core/4.8.1/build.gradle
- tests/src/org.mockito/mockito-core/4.8.1/gradle.properties
- tests/src/org.mockito/mockito-core/4.8.1/settings.gradle
- tests/src/org.mockito/mockito-core/4.8.1/src/test/java/org_mockito/mockito_core/MockitoTest.java
- tests/src/org.mockito/mockito-core/4.8.1/src/test/java/org_mockito/mockito_core/MyService.java
- tests/src/org.mockito/mockito-core/4.8.1/src/test/resources/META-INF/native-image/test/proxy-config.json
- tests/src/org.mockito/mockito-core/4.8.1/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- tests/src/org.mockito/mockito-core/4.8.1/user-code-filter.json
This only works for the 'ProxyMockMaker', which uses JDK proxies to create mocks. This method is only able to mock interfaces.
> Add metadata for Mockito 4.8.1

- library-and-framework-list.json
This adds the Neo4j-Java-Driver to the list of tested libraries and frameworks.
We use the linked repository in CI, testing all currently maintained versions of the driver.
> Add Neo4j-Java-Driver to `library-and-framework-list.json`.

- metadata/org.liquibase/liquibase-core/4.17.0/reflect-config.json
- metadata/org.liquibase/liquibase-core/4.17.0/resource-config.json
- tests/src/org.liquibase/liquibase-core/4.17.0/build.gradle
- tests/src/org.liquibase/liquibase-core/4.17.0/src/test/java/org_liquibase/liquibase_core/ExampleCustomSqlChange.java
- tests/src/org.liquibase/liquibase-core/4.17.0/src/test/java/org_liquibase/liquibase_core/ExampleCustomTaskChange.java
- tests/src/org.liquibase/liquibase-core/4.17.0/src/test/java/org_liquibase/liquibase_core/LiquibaseCoreTest.java
- tests/src/org.liquibase/liquibase-core/4.17.0/src/test/resources/META-INF/native-image/test/reflect-config.json
- tests/src/org.liquibase/liquibase-core/4.17.0/src/test/resources/META-INF/native-image/test/resource-config.json
- tests/src/org.liquibase/liquibase-core/4.17.0/src/test/resources/changelog.xml
- tests/src/org.liquibase/liquibase-core/4.17.0/src/test/resources/included.changelog.xml
- tests/src/org.liquibase/liquibase-core/4.17.0/src/test/resources/renamed.changelog.xml
This adds a complete test for all features of Liquibase and fixes the configs to make it run. It also removes the unnecessary `BeanInfo` and `Customizer` classes.
> Liquibase: XML changelogs, call all features

- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck.gradle
This could probably be improved, but it looks to me like it might be needed to persuade the JDT Language Server (used by Eclipse and VSCode) to build the project cleanly.
In VSCode you have to import one of the test projects into the workspace (probably the same in Eclipse). If you do that before this change the build will fail and you won't be able to use the Java language features in the IDE.
With this change if you run with Java 17, but not the GraalVM edition:
```
$ ./gradlew clean test -Pcoordinates=io.netty:netty-common:4.1.80.Final
> Configure project :
GraalVM Reachability Metadata TCK
---------------------------------
> Task :test-io.netty-netty-common-4.1.80.Final
====================
Testing library: io.netty:netty-common:4.1.80.Final
Command: …
```
> Add toolchain to gradle config file

- tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/TckExtension.java
As reported in [this](https://github.com/oracle/graalvm-reachability-metadata/actions/runs/3911262846/jobs/6685813930) gate there is an attempt to create a stream over the element which is null(we don't have null check for element we are trying to get from map). @melix please check if the fix can break something else in your logic here, since you are more familiar with this part of the code.
> Add null check in diffCordinates function

- metadata/org.hibernate.orm/hibernate-core/6.1.1.Final/reflect-config.json
- tests/src/org.hibernate.orm/hibernate-core/6.1.1.Final/src/test/java/org/hibernate/orm/HibernateOrmTest.java
This PR fixes an issue where the `PostgreSQLDialect` contributes types to the hibernate configuration that require reflective access to the `org.postgresql.util.PGobject` constructor which caused:
```
java.lang.NoSuchMethodException: org.postgresql.util.PGobject.<init>()
at java.base@17.0.5/java.lang.Class.getConstructor0(DynamicHub.java:3585)
at java.base@17.0.5/java.lang.Class.getConstructor(DynamicHub.java:2271)
at org.hibernate.dialect.PostgreSQLPGObjectJdbcType.<clinit>(PostgreSQLPGObjectJdbcType.java:50)
at org.hibernate.dialect.PostgreSQLDialect.registerColumnTypes(PostgreSQLDialect.java:231)
at org.hibernate.dialect.Dialect.contributeTypes(Dialect.java:1341)
at org.hibernate.dialect.PostgreSQLDialect.contributeTypes(PostgreSQLDialect.java:1229)
at …
```
> Add missing constructor hint required by hibernate PostgreSQLDialect.

- tests/src/org.opengauss/opengauss-jdbc/3.1.0-og/user-code-filter.json
- For https://github.com/oracle/graalvm-reachability-metadata/issues/166 .
- Add `user-code-filter.json` for unit tests of `org.opengauss:opengauss-jdbc`.
- I missed this issue at https://github.com/oracle/graalvm-reachability-metadata/pull/168 , which will cause confusion for future friends who try to perform tests manually. I am adding this file now.
> Add `user-code-filter.json` for unit tests of `org.opengauss:opengauss-jdbc`

- metadata/index.json
- metadata/javax.cache/cache-api/1.1.1/index.json
- metadata/javax.cache/cache-api/1.1.1/resource-config.json
- metadata/javax.cache/cache-api/1.1.1/serialization-config.json
- metadata/javax.cache/cache-api/index.json
- tests/src/index.json
- tests/src/javax.cache/cache-api/1.1.1/.gitignore
- tests/src/javax.cache/cache-api/1.1.1/build.gradle
- tests/src/javax.cache/cache-api/1.1.1/gradle.properties
- tests/src/javax.cache/cache-api/1.1.1/settings.gradle
- tests/src/javax.cache/cache-api/1.1.1/src/test/java/javax_cache/cache_api/core/CacheTest.java
- tests/src/javax.cache/cache-api/1.1.1/src/test/java/javax_cache/cache_api/core/CompletionListenerTest.java
- tests/src/javax.cache/cache-api/1.1.1/src/test/java/javax_cache/cache_api/core/EntryProcessorTest.java
- tests/src/javax.cache/cache-api/1.1.1/src/test/java/javax_cache/cache_api/core/StatisticsTest.java
- tests/src/javax.cache/cache-api/1.1.1/src/test/java/javax_cache/cache_api/core/TypeSafetyTest.java
- tests/src/javax.cache/cache-api/1.1.1/src/test/java/javax_cache/cache_api/core/stepbystep/AbstractEntryProcessor.java
- tests/src/javax.cache/cache-api/1.1.1/src/test/java/javax_cache/cache_api/core/stepbystep/MyCacheEntryListener.java
- tests/src/javax.cache/cache-api/1.1.1/src/test/java/javax_cache/cache_api/core/stepbystep/SimpleTest.java
- tests/src/javax.cache/cache-api/1.1.1/src/test/java/javax_cache/cache_api/core/stepbystep/StepTest.java
- tests/src/javax.cache/cache-api/1.1.1/src/test/java/javax_cache/cache_api/optional/CacheTest.java
- tests/src/javax.cache/cache-api/1.1.1/src/test/resources/META-INF/native-image/cache-api-test-metadata/reflect-config.json
- tests/src/javax.cache/cache-api/1.1.1/src/test/resources/META-INF/native-image/org.jsr107.ri/cache-ri-impl/jni-config.json
- tests/src/javax.cache/cache-api/1.1.1/src/test/resources/META-INF/native-image/org.jsr107.ri/cache-ri-impl/reflect-config.json
- tests/src/javax.cache/cache-api/1.1.1/user-code-filter.json
- Fixes https://github.com/oracle/graalvm-reachability-metadata/issues/136 .
- For https://github.com/oracle/graalvm-reachability-metadata/pull/169 and https://github.com/oracle/graalvm-reachability-metadata/pull/124 .
> Add support for `javax.cache:cache-api:1.1.1`

- metadata/com.hazelcast/hazelcast/5.2.1/index.json
- metadata/com.hazelcast/hazelcast/5.2.1/jni-config.json
- metadata/com.hazelcast/hazelcast/5.2.1/reflect-config.json
- metadata/com.hazelcast/hazelcast/5.2.1/resource-config.json
- metadata/com.hazelcast/hazelcast/index.json
- metadata/index.json
- tests/src/com.hazelcast/hazelcast/5.2.1/.gitignore
- tests/src/com.hazelcast/hazelcast/5.2.1/build.gradle
- tests/src/com.hazelcast/hazelcast/5.2.1/gradle.properties
- tests/src/com.hazelcast/hazelcast/5.2.1/settings.gradle
- tests/src/com.hazelcast/hazelcast/5.2.1/src/test/java/com_hazelcast/hazelcast/HazelcastTest.java
- tests/src/com.hazelcast/hazelcast/5.2.1/src/test/java/com_hazelcast/hazelcast/customSerializer/CustomSerializable.java
- tests/src/com.hazelcast/hazelcast/5.2.1/src/test/java/com_hazelcast/hazelcast/customSerializer/CustomSerializer.java
- tests/src/com.hazelcast/hazelcast/5.2.1/src/test/java/com_hazelcast/hazelcast/globalSerializer/GlobalSerializer.java
- tests/src/com.hazelcast/hazelcast/5.2.1/src/test/java/com_hazelcast/hazelcast/identifiedDataSerializable/Employee.java
- tests/src/com.hazelcast/hazelcast/5.2.1/src/test/java/com_hazelcast/hazelcast/identifiedDataSerializable/SampleDataSerializableFactory.java
- tests/src/com.hazelcast/hazelcast/5.2.1/src/test/java/com_hazelcast/hazelcast/portableSerializable/Customer.java
- tests/src/com.hazelcast/hazelcast/5.2.1/src/test/java/com_hazelcast/hazelcast/portableSerializable/SamplePortableFactory.java
- tests/src/com.hazelcast/hazelcast/5.2.1/src/test/java/com_hazelcast/hazelcast/query/ThePortableFactory.java
- tests/src/com.hazelcast/hazelcast/5.2.1/src/test/java/com_hazelcast/hazelcast/query/User.java
- tests/src/com.hazelcast/hazelcast/5.2.1/user-code-filter.json
- tests/src/index.json
- Fixes https://github.com/oracle/graalvm-reachability-metadata/issues/32  .
- Fixes https://github.com/oracle/graalvm-reachability-metadata/pull/122 .
- This is part of https://github.com/oracle/graalvm-reachability-metadata/issues/117 .
> Add support for `com.hazelcast:hazelcast:5.2.1`

- .github/workflows/test-changed-metadata.yml
Disable PR reports that [can quickly spam PRs](https://github.com/oracle/graalvm-reachability-metadata/pull/173#issuecomment-1382088594) when run across all metadata.
> Disable Native Image PR reports.

- metadata/org.hibernate.validator/hibernate-validator/7.0.4.Final/reflect-config.json
Similar to the problem with Hibernate that #113 fixed, Hibernate Validator's metadata contains entries for various MBean-related classes. This metadata causes a call to
`ManagementFactory.getPlatformMBeanServer()` to fail with a `javax.management.openmbean.OpenDataException`. It would appear that the metadata is sufficient for the bootstrapping of the MBean server to take a different code path to normal and this path fails. This PR removes the offending metadata which fixes `ManagementFactory.getPlatformMBeanServer()` and has no adverse effects on the existing tests for hibernate-validator.
No new tests have been added but the existing tests are unaffected by the changes.
> Remove MBean-related reflection entries from hibernate-validator

- metadata/io.undertow/undertow-core/2.2.19.Final/reflect-config.json
Similar to the problem with Hibernate that #113 fixed, Undertow's metadata contains entries for various MBean-related classes. This metadata causes a call to
`ManagementFactory.getPlatformMBeanServer()` to [fail with a `javax.management.openmbean.OpenDataException`](https://github.com/spring-projects/spring-boot/issues/33677). It would appear that the metadata is sufficient for the bootstrapping of the MBean server to take a different code path to normal and this path fails. This PR removes the offending metadata which fixes `ManagementFactory.getPlatformMBeanServer()` and has no adverse effects on the existing tests for hibernate-core.
No new tests have been added but the existing tests are unaffected by the changes.
> Remove MBean-related reflection entries from undertow-core

- metadata/com.google.protobuf/protobuf-java-util/3.21.12/index.json
- metadata/com.google.protobuf/protobuf-java-util/3.21.12/reflect-config.json
- metadata/com.google.protobuf/protobuf-java-util/index.json
- metadata/index.json
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/.gitignore
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/build.gradle
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/gradle.properties
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/settings.gradle
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com/google/protobuf/util/DurationsTest.java
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com/google/protobuf/util/FieldMaskTreeTest.java
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com/google/protobuf/util/JsonFormatTest.java
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com/google/protobuf/util/TimestampsTest.java
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com_google_protobuf/protobuf_java_util/FieldMaskUtilTest.java
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com_google_protobuf/protobuf_java_util/StructsTest.java
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/java/com_google_protobuf/protobuf_java_util/ValuesTest.java
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/proto/com_google_protobuf/protobuf_java_util/json_test.proto
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/proto/com_google_protobuf/protobuf_java_util/unittest.proto
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/proto/com_google_protobuf/protobuf_java_util/unittest_import.proto
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/proto/com_google_protobuf/protobuf_java_util/unittest_import_public.proto
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/src/test/resources/META-INF/native-image/protobuf-java-util-test-metadata/reflect-config.json
- tests/src/com.google.protobuf/protobuf-java-util/3.21.12/user-code-filter.json
- tests/src/index.json
- Fixes https://github.com/oracle/graalvm-reachability-metadata/issues/165 .
> Add support for `com.google.protobuf:protobuf-java-util:3.21.12`

- .github/workflows/test-all-metadata.yml
- .github/workflows/test-changed-metadata.yml
- gradle/wrapper/gradle-wrapper.properties
- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck.gradle
Fix Ci `not supported Java version` error.
> Fix Not Supported Java Version Bug

- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck.gradle
This commit fixes the metadata repository not being used in the TCK. Before, it was assumed that each test was working in isolation, but in practice, #211 showed that it is not the case.
So instead of the TCK figuring out by itself which metadata config to include, and completely ignoring the "requires" clauses, we will now simply configure the tests to use the metadata from the current state of the repository. It makes things easier, at the cost of possible side effects: it is possible that the metadata from a transitive dependency is actually what makes a build pass.
However this drawback should be covered by regular code reviews, as it is unexpected that metadata for a transitive "talks" about the current module under test.
Fixes #211
> Fix "requires" clauses being ignored

- tests/src/org.eclipse.jetty/jetty-client/11.0.12/build.gradle
- tests/src/org.eclipse.jetty/jetty-server/11.0.12/build.gradle
- tests/src/org.jetbrains.kotlin/kotlin-reflect/1.7.10/build.gradle
- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
- Fixes https://github.com/oracle/graalvm-reachability-metadata/issues/207 .
- Setting the target JVM version for Kotlin Reflect. Refer to https://github.com/gradle/gradle/issues/22653 , https://kotlinlang.org/docs/gradle-compiler-options.html#how-to-define-options and https://kotlinlang.org/docs/whatsnew18.html#exposing-kotlin-compiler-options-as-gradle-lazy-properties .
- Looks like `gradle-wrapper.jar` cannot be excluded in Git.
> Restore JDK19 testing for GitHub Actions

- metadata/index.json
- metadata/jakarta.servlet/jakarta.servlet-api/5.0.0/index.json
- metadata/jakarta.servlet/jakarta.servlet-api/5.0.0/resource-config.json
- metadata/jakarta.servlet/jakarta.servlet-api/index.json
- tests/src/index.json
- tests/src/jakarta.servlet/jakarta.servlet-api/5.0.0/.gitignore
- tests/src/jakarta.servlet/jakarta.servlet-api/5.0.0/build.gradle
- tests/src/jakarta.servlet/jakarta.servlet-api/5.0.0/gradle.properties
- tests/src/jakarta.servlet/jakarta.servlet-api/5.0.0/settings.gradle
- tests/src/jakarta.servlet/jakarta.servlet-api/5.0.0/src/test/java/jakarta_servlet/jakarta_servlet_api/JakartaServletTests.java
This PR adds metadata for the Jakarta Servlet API 5.0.0+ dependency.
> Add metadata for Jakarta Servlet API

- tests/src/org.thymeleaf/thymeleaf-spring6/3.1.0.M2/build.gradle
Spring 6.0 milestones versions were using internal GraalVM
for its `ConstantReadableJavaField`, which has been replaced by
`PreComputeFieldFeature` in the RC phase.
This commit upgrades the Spring version being used in the Thymeleaf
Spring tests to avoid referencing internal GraalVM APIs.
Fixes gh-230
> Upgrade Spring version in Thymeleaf Spring tests

- metadata/com.graphql-java/graphql-java-extended-validation/19.1/index.json
- metadata/com.graphql-java/graphql-java-extended-validation/19.1/proxy-config.json
- metadata/com.graphql-java/graphql-java-extended-validation/19.1/reflect-config.json
- metadata/com.graphql-java/graphql-java-extended-validation/19.1/resource-config.json
- metadata/com.graphql-java/graphql-java-extended-validation/index.json
- metadata/index.json
- tests/src/com.graphql-java/graphql-java-extended-validation/19.1/.gitignore
- tests/src/com.graphql-java/graphql-java-extended-validation/19.1/build.gradle
- tests/src/com.graphql-java/graphql-java-extended-validation/19.1/gradle.properties
- tests/src/com.graphql-java/graphql-java-extended-validation/19.1/settings.gradle
- tests/src/com.graphql-java/graphql-java-extended-validation/19.1/src/test/java/graphql/GraphQlValidationTests.java
- tests/src/com.graphql-java/graphql-java-extended-validation/19.1/src/test/resources/META-INF/native-image/graphql-validation-test-metadata/resource-config.json
- tests/src/com.graphql-java/graphql-java-extended-validation/19.1/src/test/resources/graphql/validation.graphqls
- tests/src/com.graphql-java/graphql-java-extended-validation/19.1/src/test/resources/graphql/validation/ValidationMessages_fr.properties
- tests/src/index.json
This PR builds on the existing graphql-java metadata and adds the relevant content for the graphql-java-extended-validation artifact.
document)
> Add metadata for graphql-java-extended-validation

- metadata/org.hdrhistogram/HdrHistogram/2.1.12/reflect-config.json
- tests/src/org.hdrhistogram/HdrHistogram/2.1.12/src/test/java/hdrhistogram/HdrHistogramTest.java
This PR adds reflection config for the `ConcurrentHistogram(AbstractHistogram)` constructor.
Closes gh-234
> Add reflection config for ConcurrentHistogram(AbstractHistogram)

- metadata/org.jetbrains.kotlin/kotlin-reflect/1.7.10/reflect-config.json
- tests/src/org.jetbrains.kotlin/kotlin-reflect/1.7.10/build.gradle
- tests/src/org.jetbrains.kotlin/kotlin-reflect/1.7.10/src/test/kotlin/kotlinreflect/KotlinReflectTests.kt
Adds `kotlin.internal.jdk8.JDK8PlatformImplementations constructor` to `reflect-config.json`.
It is required when using coroutines.
> Added kotlin.internal.jdk8.JDK8PlatformImplementations constructor.

- metadata/index.json
- metadata/io.undertow/undertow-core/2.2.19.Final/resource-config.json
- metadata/org.jboss.spec.javax.servlet/jboss-servlet-api_4.0_spec/2.0.0.Final/index.json
- metadata/org.jboss.spec.javax.servlet/jboss-servlet-api_4.0_spec/2.0.0.Final/resource-config.json
- metadata/org.jboss.spec.javax.servlet/jboss-servlet-api_4.0_spec/index.json
- tests/src/index.json
- tests/src/org.jboss.spec.javax.servlet/jboss-servlet-api_4.0_spec/2.0.0.Final/.gitignore
- tests/src/org.jboss.spec.javax.servlet/jboss-servlet-api_4.0_spec/2.0.0.Final/build.gradle
- tests/src/org.jboss.spec.javax.servlet/jboss-servlet-api_4.0_spec/2.0.0.Final/gradle.properties
- tests/src/org.jboss.spec.javax.servlet/jboss-servlet-api_4.0_spec/2.0.0.Final/settings.gradle
- tests/src/org.jboss.spec.javax.servlet/jboss-servlet-api_4.0_spec/2.0.0.Final/src/test/java/jboss/servletspec/JbossServletSpecTests.java
This adds reachability metadata for the
`org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final` dependency and removes the duplicate metadata from the undertow one. As of undertow 2.3, undertow is using the Jakarta servlet spec.
> Add metadata for Jboss Servlet API 4.0

- tests/tck-build-logic/src/main/resources/AllowedDockerImages.txt
```
grype mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
✔ Vulnerability DB        [updated]
✔ Loaded image            
✔ Parsed image            
✔ Cataloged packages      [184 packages]
✔ Scanning image...       [182 vulnerabilities]
├── 0 critical, 2 high, 129 medium, 32 low, 19 negligible
└── 152 fixed
NAME                  INSTALLED                     FIXED-IN                      TYPE  VULNERABILITY   SEVERITY   
ca-certificates       20210119~20.04.2              20211016ubuntu0.20.04.1       deb   CVE-2022-23491  Medium      
coreutils             8.30-3ubuntu2                                               deb   CVE-2016-2781   Low         
e2fsprogs             1.45.5-2ubuntu1               1.45.5-2ubuntu1.1             deb   CVE-2022-1304   Medium      
gdb …
```
> Added mssql docker image to the allowed images list

- tests/src/org.eclipse.jetty/jetty-client/11.0.12/src/test/java/org_eclipse_jetty/jetty_client/JettyClientTest.java
Disables JettyClientTest. This test communicates with some external service so it should be disabled until it is refactored.
> Disable jetty test

- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck.gradle
This commit lets the user set a couple of environement variables to tweak which JDK will be used to compile the tests and build the native binaries:
- TCK_JAVA_VERSION should be set to the language version, eg. 20
- TCK_JAVA_VENDOR should be set to the vendor, e.g Oracle
> Let the user override the default toolchain

- metadata/index.json
- metadata/org.jetbrains.kotlin/kotlin-reflect/1.7.10/reflect-config.json
- metadata/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/index.json
- metadata/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/reflect-config.json
- metadata/org.jetbrains.kotlin/kotlin-stdlib/index.json
- tests/src/index.json
- tests/src/org.jetbrains.kotlin/kotlin-reflect/1.7.10/src/test/kotlin/kotlinreflect/KotlinReflectTests.kt
- tests/src/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/build.gradle
- tests/src/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/gradle.properties
- tests/src/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/settings.gradle
- tests/src/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/src/test/kotlin/kotlinstdlib/KotlinStdlibTests.kt
Adds metadata for `kotlin.internal.jdk8.JDK8PlatformImplementations` when using `kotlin-stdlib`.
> Move kotlin.internal.jdk8.JDK8PlatformImplementations to kotlin-stdlib.

- metadata/com.zaxxer/HikariCP/5.0.1/reflect-config.json
- tests/src/com.zaxxer/HikariCP/5.0.1/build.gradle
- tests/src/com.zaxxer/HikariCP/5.0.1/src/test/resources/logback.xml
Adds more metadata for com.zaxxer:HikariCP:5.0.1
> Added more metadata for com.zaxxer:HikariCP:5.0.1

- CONTRIBUTING.md
- metadata/org.hibernate.orm/hibernate-core/index.json
This new `index.json` attribute is design to allow more flexible version matching to avoid breakage due to switching on the latest version for untested ones.
It should have a `default-for` key and a regexp as a string value, for example `"1\\.0\\..*"` which should match versions like 1.0.0, 1.0.1, 1.0.2, etc.
See graalvm/native-build-tools#432
Closes #62
> Add support for `default-for` attribute

- metadata/org.hibernate.orm/hibernate-core/6.2.0.Final/reflect-config.json
- metadata/org.hibernate.orm/hibernate-core/index.json
This commit adds additional reflection entries for logger that are required due to https://hibernate.atlassian.net/browse/HHH-16507 and https://hibernate.atlassian.net/browse/HHH-16441 to fix compatibility with Hibernate 6.2.2.
I chose to not create a dedicated new version for maintanablity reasons and because those hints are triggered by `typeReachable` condition that allow to support both 6.2.0 and 6.2.2.
> Fix compatibility with Hibernate 6.2.2

- metadata/org.quartz-scheduler/quartz/2.3.2/resource-config.json
- tests/src/org.quartz-scheduler/quartz/2.3.2/src/test/java/quartz/QuartzTest.java
- tests/src/org.quartz-scheduler/quartz/2.3.2/src/test/java/quartz/SimpleJob.java
fe74d0e8 added a type reachable condition for Quartz's SQL resource files but the type that was used (org.quartz.SimpleJob) isn't part of Quartz and only exists in the tests for the Quartz metadata.
Updates the tests to reveal the problem by moving their classes out of the org.quartz namespace and updates the metadata to use a type in the condition that's part of Quartz.
> Correct type reachable condition in Quartz resource config

- metadata/org.testcontainers/testcontainers/1.17.6/reflect-config.json
When using Testcontainers in a native image and a `~/.docker/config.json` file is present, a failure occurs:
```
Failures (1):
JUnit Jupiter:TcdemoApplicationTests
ClassSource [className = 'com.example.tcdemo.TcdemoApplicationTests', filePosition = null]
=> java.util.ServiceConfigurationError: org.testcontainers.dockerclient.DockerClientProviderStrategy: Provider org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy could not be instantiated
java.base@17.0.5/java.util.ServiceLoader.fail(ServiceLoader.java:586)
java.base@17.0.5/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
java.base@17.0.5/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
java.base@17.0.5/java.util.ServiceLoader$3.next(ServiceLoader.java:1403) …
```
> Allow Testcontainers to create DockerConfigFile from json using Jackson

- metadata/com.graphql-java/graphql-java/19.2/reflect-config.json
- tests/src/com.graphql-java/graphql-java/19.2/src/test/java/graphql/GraphQlTests.java
- tests/src/com.graphql-java/graphql-java/19.2/src/test/java/graphql/starwars/Human.java
- tests/src/com.graphql-java/graphql-java/19.2/src/test/resources/META-INF/native-image/graphql-test-metadata/reflect-config.json
- tests/src/com.graphql-java/graphql-java/19.2/src/test/resources/graphql/starwars.graphqls
GraphQL Java ships interfaces for the Relay spec, as well as default
implementations for those types: Connection, Edge, PageInfo,
ConnectionCursor.
This commits adds reflection metadata for default implementations since
they are likely to be used when the GraphQL schema leverages the
interfaces provided by GraphQL Java.
[CONTRIBUTING](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md) document)
> Add reflection for default Relay types in GraphQL Java

- metadata/commons-logging/commons-logging/1.2/index.json
- metadata/commons-logging/commons-logging/1.2/reflect-config.json
- metadata/commons-logging/commons-logging/index.json
- metadata/index.json
- tests/src/commons-logging/commons-logging/1.2/.gitignore
- tests/src/commons-logging/commons-logging/1.2/build.gradle
- tests/src/commons-logging/commons-logging/1.2/gradle.properties
- tests/src/commons-logging/commons-logging/1.2/metadata-extra-filter.json
- tests/src/commons-logging/commons-logging/1.2/metadata-user-code-filter.json
- tests/src/commons-logging/commons-logging/1.2/settings.gradle
- tests/src/commons-logging/commons-logging/1.2/src/test/java/commons_logging/commons_logging/CommonsLoggingTest.java
- tests/src/index.json
Adds metadata for commons-logging:commons-logging:1.2
> Added metadata for commons-logging:commons-logging:1.2

- metadata/index.json
- metadata/org.apache.httpcomponents/httpclient/4.5.14/index.json
- metadata/org.apache.httpcomponents/httpclient/4.5.14/reflect-config.json
- metadata/org.apache.httpcomponents/httpclient/4.5.14/resource-config.json
- metadata/org.apache.httpcomponents/httpclient/4.5.14/serialization-config.json
- metadata/org.apache.httpcomponents/httpclient/index.json
- tests/src/index.json
- tests/src/org.apache.httpcomponents/httpclient/4.5.14/.gitignore
- tests/src/org.apache.httpcomponents/httpclient/4.5.14/build.gradle
- tests/src/org.apache.httpcomponents/httpclient/4.5.14/gradle.properties
- tests/src/org.apache.httpcomponents/httpclient/4.5.14/required-docker-images.txt
- tests/src/org.apache.httpcomponents/httpclient/4.5.14/settings.gradle
- tests/src/org.apache.httpcomponents/httpclient/4.5.14/src/test/java/org_apache_httpcomponents/httpclient/HttpClientTest.java
Adds metadata for org.apache.httpcomponents:httpclient:4.5.14
> Added metadata for org.apache.httpcomponents:httpclient:4.5.14

- .github/workflows/checkstyle.yml
- .github/workflows/scan-docker-images.yml
- .github/workflows/test-all-metadata.yml
- .github/workflows/test-changed-metadata.yml
- gradle/libs.versions.toml
- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck.gradle
This PR upgrade the NBT to `0.9.23` and updates all uses of the `setup-graalvm` action to use the new GraalVM for JDK 17 release.
n/a
> Upgrade Native Build Tools and update to GraalVM for JDK 17.

- library-and-framework-list.json
Adds OCI Java SDK to the list of libraries supporting native image
> Add OCI Java SDK to the list of libraries supporting native image

- tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/GrypeTask.java
This should be reverted as soon as we merge [this](https://github.com/oracle/graalvm-reachability-metadata/pull/329) PR. This is just a PR that unblocks the gates temporarily
> Increase number of allowed high vulnerabilities to unblock gates

- .github/workflows/checkstyle-skip.yml
- .github/workflows/checkstyle.yml
- .github/workflows/library-and-framework-list-validation-skip.yml
- .github/workflows/library-and-framework-list-validation.yml
- .github/workflows/scan-docker-images-skip.yml
- .github/workflows/scan-docker-images.yml
- .github/workflows/test-all-metadata-skip.yml
- .github/workflows/test-all-metadata.yml
- .github/workflows/test-changed-metadata-skip.yml
- .github/workflows/test-changed-metadata.yml
This PR adjusts the workflow configs so that they use `paths` and `paths-ignore` to target specific tests. For example, there is no need to test the `library-and-framework-list.json` every time someone changes metadata, and vice versa. Similarly, we don't want to run all tests when changing documentation (markdown files).
> Add `paths(-ignore)` filters to reduce test overhead.

- library-and-framework-list.json
> Update library-and-framework-list.json with OCI APM Related details

- tests/src/com.sun.mail/jakarta.mail/2.0.1/required-docker-images.txt
- tests/src/com.sun.mail/jakarta.mail/2.0.1/src/test/java/com/sun/mail/JakartaMailTest.java
- tests/tck-build-logic/src/main/resources/AllowedDockerImages.txt
Replaces greenmail docker image that caused [gates failure](https://github.com/oracle/graalvm-reachability-metadata/actions/runs/5409930791/jobs/9830696478#step:4:66), with the newer one with less vulnerabilities.
``` shell
grype greenmail/standalone:2.1.0-alpha-1
✔ Vulnerability DB        [no update available]
New version of grype is available: 0.63.0 (currently running: 0.58.0)
✔ Loaded image            
✔ Parsed image            
✔ Cataloged packages      [188 packages]
✔ Scanned image           [66 vulnerabilities]
NAME                   INSTALLED                 FIXED-IN                   TYPE          VULNERABILITY   SEVERITY   
bash                   5.1-6ubuntu1                                         deb           CVE-2022-3715   Low         
coreutils …
```
> Replace greenmail/standalone docker image with the less vulnerable version

- tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/GrypeTask.java
Follow up [this PR](https://github.com/oracle/graalvm-reachability-metadata/pull/329). It reverts changes from [this PR](https://github.com/oracle/graalvm-reachability-metadata/pull/337) which was quick fix
> Set number of allowed high vulnerabilities to previous state

- tests/tck-build-logic/src/main/resources/AllowedDockerImages.txt
```
grype eclipse-mosquitto:2.0.15
✔ Vulnerability DB        [updated]
✔ Loaded image            
✔ Parsed image            
✔ Cataloged packages      [22 packages]
✔ Scanning image...       [0 vulnerabilities]
├── 0 critical, 0 high, 0 medium, 0 low, 0 negligible
└── 0 fixed
```
> Added eclipse-mosquitto:2.0.15 to the list of allowed docker images

- tests/src/com.mysql/mysql-connector-j/8.0.31/required-docker-images.txt
- tests/src/com.mysql/mysql-connector-j/8.0.31/src/test/java/mysql/MySQLTests.java
- tests/src/mysql/mysql-connector-java/8.0.29/required-docker-images.txt
- tests/src/mysql/mysql-connector-java/8.0.29/src/test/java/mysql/MySQLTests.java
- tests/src/org.hibernate.reactive/hibernate-reactive-core/2.0.0.Final/required-docker-images.txt
- tests/src/org.hibernate.reactive/hibernate-reactive-core/2.0.0.Final/src/test/java/org_hibernate_reactive/hibernate_reactive_core/HibernateReactiveCoreTest.java
- tests/src/samples/docker/image-pull/required-docker-images.txt
- tests/src/samples/docker/image-pull/src/test/java/image/pull/DockerImagePullTests.java
- tests/tck-build-logic/src/main/resources/AllowedDockerImages.txt
Change docker image to the official one from [oracle repository](https://container-registry.oracle.com/ords/f?p=113:10::::::)
```
grype container-registry.oracle.com/mysql/community-server:8.1
✔ Vulnerability DB        [no update available]
New version of grype is available: 0.64.2 (currently running: 0.58.0)
✔ Loaded image            
✔ Parsed image            
✔ Cataloged packages      [135 packages]
✔ Scanned image           [11 vulnerabilities]
NAME          INSTALLED       FIXED-IN                  TYPE    VULNERABILITY        SEVERITY 
certifi       2022.12.7       2022.12.07                python  GHSA-43fp-rhv2-5gv8  Medium    
cryptography  39.0.2          41.0.0                    python  GHSA-5cpq-8wj7-hf2v  Low       
cryptography  39.0.2          41.0.2 …
```
> Change docker image to the official one from oracle repository

- metadata/index.json
- tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/ConfigFilesChecker.java
Currently we are looking for `allowedPackages` field in `metdata/index.json` by searching for the `groupId` in the module name of the corresponding library. It turns out that this approach misses corner case when two libraries have the same `groupId` but different `artifactId` (Example: `org.eclipse.paho:org.eclipse.paho.client.mqttv3` and `org.eclipse.paho:org.eclipse.paho.mqttv5.client`). This PR narrows the search by looking for both `groupId` and `artifactId` in the module name.
> Narrow the search in getAllowedPackages function

- CONTRIBUTING.md
- tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/DockerUtils.java
- tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/GrypeTask.java
- tests/tck-build-logic/src/main/resources/AllowedDockerImages.txt
This is a follow-up PR of [this PR](https://github.com/oracle/graalvm-reachability-metadata/pull/351). It removes usage of `AllowedDockerImages.txt` and introduces a new way we are collecting allowed docker images list.
n/a
> Adjust docker and grype tasks

- metadata/index.json
- metadata/org.apache.commons/commons-compress/1.23.0/index.json
- metadata/org.apache.commons/commons-compress/1.23.0/reflect-config.json
- metadata/org.apache.commons/commons-compress/index.json
- tests/src/index.json
- tests/src/org.apache.commons/commons-compress/1.23.0/.gitignore
- tests/src/org.apache.commons/commons-compress/1.23.0/build.gradle
- tests/src/org.apache.commons/commons-compress/1.23.0/gradle.properties
- tests/src/org.apache.commons/commons-compress/1.23.0/metadata-user-code-filter.json
- tests/src/org.apache.commons/commons-compress/1.23.0/settings.gradle
- tests/src/org.apache.commons/commons-compress/1.23.0/src/test/java/org_apache_commons/commons_compress/CommonsCompressTest.java
Adds metadata for `org.apache.commons:commons-compress:1.23.0`
- The `CommonsCompressTest` creates a test directory in the `tmp` folder and deletes it at the end of the test execution.
> Added metadata for org.apache.commons:commons-compress:1.23.0

- metadata/index.json
- metadata/org.eclipse.jgit/org.eclipse.jgit/6.5.0.202303070854-r/index.json
- metadata/org.eclipse.jgit/org.eclipse.jgit/6.5.0.202303070854-r/reflect-config.json
- metadata/org.eclipse.jgit/org.eclipse.jgit/6.5.0.202303070854-r/resource-config.json
- metadata/org.eclipse.jgit/org.eclipse.jgit/index.json
- tests/src/index.json
- tests/src/org.eclipse.jgit/org.eclipse.jgit/6.5.0.202303070854-r/.gitignore
- tests/src/org.eclipse.jgit/org.eclipse.jgit/6.5.0.202303070854-r/build.gradle
- tests/src/org.eclipse.jgit/org.eclipse.jgit/6.5.0.202303070854-r/gradle.properties
- tests/src/org.eclipse.jgit/org.eclipse.jgit/6.5.0.202303070854-r/metadata-extra-filter.json
- tests/src/org.eclipse.jgit/org.eclipse.jgit/6.5.0.202303070854-r/metadata-user-code-filter.json
- tests/src/org.eclipse.jgit/org.eclipse.jgit/6.5.0.202303070854-r/settings.gradle
- tests/src/org.eclipse.jgit/org.eclipse.jgit/6.5.0.202303070854-r/src/test/java/org_eclipse_jgit/org_eclipse_jgit/OrgEclipseJGitTest.java
- tests/src/org.eclipse.jgit/org.eclipse.jgit/6.5.0.202303070854-r/src/test/resources/META-INF/native-image/jgit-tests-only/resource-config.json
- tests/src/org.eclipse.jgit/org.eclipse.jgit/6.5.0.202303070854-r/src/test/resources/logback.xml
Adds metadata for `org.eclipse.jgit:org.eclipse.jgit:6.5.0.202303070854-r`
- The `OrgEclipseJGitTest` creates two git repositories in the `tmp` folder and deletes it at the end of the test execution.
> Added metadata for org.eclipse.jgit:org.eclipse.jgit:6.5.0.202303070854-r

- metadata/index.json
- metadata/org.apache.kafka/kafka-clients/3.5.1/index.json
- metadata/org.apache.kafka/kafka-clients/3.5.1/reflect-config.json
- metadata/org.apache.kafka/kafka-clients/3.5.1/resource-config.json
- metadata/org.apache.kafka/kafka-clients/index.json
- tests/src/index.json
- tests/src/org.apache.kafka/kafka-clients/3.5.1/.gitignore
- tests/src/org.apache.kafka/kafka-clients/3.5.1/build.gradle
- tests/src/org.apache.kafka/kafka-clients/3.5.1/gradle.properties
- tests/src/org.apache.kafka/kafka-clients/3.5.1/metadata-extra-filter.json
- tests/src/org.apache.kafka/kafka-clients/3.5.1/metadata-user-code-filter.json
- tests/src/org.apache.kafka/kafka-clients/3.5.1/settings.gradle
- tests/src/org.apache.kafka/kafka-clients/3.5.1/src/test/java/org_apache_kafka/kafka_clients/KafkaClientsTest.java
- tests/src/org.apache.kafka/kafka-clients/3.5.1/src/test/resources/META-INF/native-image/kafka-tests-only/reflect-config.json
- tests/src/org.apache.kafka/kafka-clients/3.5.1/src/test/resources/META-INF/native-image/kafka-tests-only/resource-config.json
- tests/src/org.apache.kafka/kafka-clients/3.5.1/src/test/resources/logback.xml
Adds metadata for org.apache.kafka:kafka-clients:3.5.1
> Added metadata for org.apache.kafka:kafka-clients:3.5.1

- metadata/io.netty/netty-common/4.1.80.Final/jni-config.json
- metadata/io.netty/netty-common/4.1.80.Final/reflect-config.json
- metadata/io.netty/netty-common/4.1.80.Final/resource-config.json
This PR adds metadata for Netty KQueue transport.
Netty KQueue transport can be used by the users that are on Mac OS and do not want to use Java NIO transport. (similar to Epoll transport for Linux)
N/A
- N/A [ ] For all tests where I am not the sole author, I have added a comment that proves I may publish them under the specified license (see [the tests section from our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#tests))
- N/A [ ] I have added thorough tests (see [the tests section from our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))
- N/A [ ] I have filled all places where my pull request accesses files, network, docker, or any other external service (see …
> Add metadata for Netty KQueue transport

- metadata/org.eclipse.jetty/jetty-server/12.0.1/index.json
- metadata/org.eclipse.jetty/jetty-server/12.0.1/reflect-config.json
- metadata/org.eclipse.jetty/jetty-server/12.0.1/resource-config.json
- metadata/org.eclipse.jetty/jetty-server/index.json
- tests/src/index.json
- tests/src/org.eclipse.jetty/jetty-server/12.0.1/.gitignore
- tests/src/org.eclipse.jetty/jetty-server/12.0.1/README.md
- tests/src/org.eclipse.jetty/jetty-server/12.0.1/build.gradle
- tests/src/org.eclipse.jetty/jetty-server/12.0.1/gradle.properties
- tests/src/org.eclipse.jetty/jetty-server/12.0.1/settings.gradle
- tests/src/org.eclipse.jetty/jetty-server/12.0.1/src/test/java/jetty/HelloWorldServlet.java
- tests/src/org.eclipse.jetty/jetty-server/12.0.1/src/test/java/jetty/JettyTests.java
- tests/src/org.eclipse.jetty/jetty-server/12.0.1/src/test/resources/META-INF/native-image/test/reflect-config.json
- tests/src/org.eclipse.jetty/jetty-server/12.0.1/user-code-filter.json
Add metadata for Jetty 12.
- Starts a Jetty server inside the test and then accesses it with the `HttpClient`.
> Add metadata for Jetty 12

- library-and-framework-list.json
With version 3.9 avaje-config includes the native-image metadata in with the library in
META-INF/native-image/io.avaje.config.avaje-config
Add io.avaje:avaje-config to library-and-framework-list.json
> Add io.avaje:avaje-config to library-and-framework-list.json

- library-and-framework-list.json
Adds avaje-validator library to library-and-framework-list.json.
Avaje validator has:
- Added a `resource-config.json` with `bundles`
- Added a native image specific test building a native image with DE and EN locales via `-H:IncludeLocales=de,en` and confirms that the error message from the bundles are used as expected
> Add Avaje Validator to library-and-framework-list.json

- library-and-framework-list-schema.json
- library-and-framework-list.json
PR for https://github.com/oracle/graalvm-reachability-metadata/issues/151
N/A
> Adding the AWS SDK v2.0

- library-and-framework-list.json
With version 13.10.0 ebean-migration includes the native-image metadata in with the library in META-INF/native-image/io.ebean.migration.ebean-migration
Add io.ebean:ebean-migration to library-and-framework-list.json
> Add io.ebean:ebean-migration to library-and-framework-list.json

- .github/workflows/scan-docker-images.yml
Weekly docker image scan should be run only on origin repository and not on forks
> Only Run Weekly Docker Image Scan on Origin

- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
Adds GraalVM for JDK 21 to the test matrix.
- n/a
> Run tests against GraalVM for JDK 21.

- metadata/io.netty/netty-common/4.1.80.Final/reflect-config.json
- tests/src/io.netty/netty-common/4.1.80.Final/src/test/java/netty/NettyTests.java
Add reflection hints for Netty SelectorProviderUtil
Netty code in `io.netty.channel.socket.nio.SelectorProviderUtil`:
```java
@SuppressJava6Requirement(reason = "Usage guarded by java version check")
static Method findOpenMethod(String methodName) {
if (PlatformDependent.javaVersion() >= 15) {
try {
return SelectorProvider.class.getMethod(methodName, java.net.ProtocolFamily.class);
} catch (Throwable e) {
logger.debug("SelectorProvider.{}(ProtocolFamily) not available, will use default", methodName, e);
}
}
return null;
}
```
If Java version higher than or equals to 15, `SelectorProviderUtil` may invoke `java.nio.channels.spi.SelectorProvide` by reflection.
`SelectorProviderUtil.findOpenMethod` will be called in two Netty class: `NioSocketChannel` and `NioServerSocketChannel` …
> Add metadata for Netty SelectorProviderUtil

- metadata/com.github.ben-manes.caffeine/caffeine/2.9.3/index.json
- metadata/com.github.ben-manes.caffeine/caffeine/2.9.3/reflect-config.json
- metadata/com.github.ben-manes.caffeine/caffeine/index.json
- tests/src/com.github.ben-manes.caffeine/caffeine/2.9.3/.gitignore
- tests/src/com.github.ben-manes.caffeine/caffeine/2.9.3/build.gradle
- tests/src/com.github.ben-manes.caffeine/caffeine/2.9.3/gradle.properties
- tests/src/com.github.ben-manes.caffeine/caffeine/2.9.3/settings.gradle
- tests/src/com.github.ben-manes.caffeine/caffeine/2.9.3/src/test/java/com_github_ben_manes_caffeine/caffeine/CaffeineTest.java
- tests/src/com.github.ben-manes.caffeine/caffeine/2.9.3/src/test/java/com_github_ben_manes_caffeine/caffeine/EvictionTest.java
- tests/src/com.github.ben-manes.caffeine/caffeine/2.9.3/src/test/java/com_github_ben_manes_caffeine/caffeine/PolicyTest.java
- tests/src/com.github.ben-manes.caffeine/caffeine/2.9.3/src/test/java/com_github_ben_manes_caffeine/caffeine/PopulationTest.java
- tests/src/com.github.ben-manes.caffeine/caffeine/2.9.3/src/test/java/com_github_ben_manes_caffeine/caffeine/RemovalTest.java
- tests/src/com.github.ben-manes.caffeine/caffeine/2.9.3/src/test/java/com_github_ben_manes_caffeine/caffeine/TestRefreshLoader.java
- tests/src/com.github.ben-manes.caffeine/caffeine/2.9.3/user-code-filter.json
- tests/src/index.json
- Fixes #384 .
- Add support for `com.github.ben-manes.caffeine:caffeine:2.9.3`.
- According to my test at https://github.com/linghengqian/graalvm-trace-metadata-smoketest/commit/2f29acb8845ddde5c3fc7d3d6072dfd8f5574f48 and https://github.com/linghengqian/graalvm-trace-metadata-smoketest/commit/15ef51ecf88beb819e3844c634b35b115da37a52,  the test results of the APIs of `2.9.3` and `3.1.2` are quite inconsistent.
- This PR is related to the Error detected at https://github.com/apache/shardingsphere/issues/21347 .
- Null.
> Add support for `com.github.ben-manes.caffeine:caffeine:2.9.3`

- metadata/ch.qos.logback/logback-classic/1.4.9/reflect-config.json
Fixes gh-454
Allows Logback to load `BasicConfigurator` using reflection.
None.
> Allow Logback to load its BasicConfigurator using reflection

- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
It adds the ability to ignore matrix defaults via:
```bash
./gradlew generateMatrixMatchingCoordinates -Pcoordinates=all -PignoreDefaults
```
> Add ability to ignore matrix defaults.

- metadata/org.apache.kafka/kafka-streams/3.5.1/reflect-config.json
* Adding a few missing hints in Kafka Streams version 3.7.0
- Missing hints for BuiltInDslStoreSuppliers$RocksDBDslStoreSuppliers
- Missing hints for BuiltInDslStoreSuppliers$InMemoryDslStoreSuppliers
> Adding Kafka Streams 3.7.0 missing hints

- metadata/org.hibernate.reactive/hibernate-reactive-core/2.0.0.Final/reflect-config.json
- tests/src/org.hibernate.reactive/hibernate-reactive-core/2.0.0.Final/src/test/java/org_hibernate_reactive/hibernate_reactive_core/HibernateReactiveCoreTest.java
- tests/src/org.hibernate.reactive/hibernate-reactive-core/2.0.0.Final/src/test/java/org_hibernate_reactive/hibernate_reactive_core/entity/Course.java
- tests/src/org.hibernate.reactive/hibernate-reactive-core/2.0.0.Final/src/test/java/org_hibernate_reactive/hibernate_reactive_core/entity/Student.java
- tests/src/org.hibernate.reactive/hibernate-reactive-core/2.0.0.Final/src/test/resources/META-INF/native-image/hibernate-reactive-core-tests-only/reflect-config.json
- tests/src/org.hibernate.reactive/hibernate-reactive-core/2.0.0.Final/src/test/resources/META-INF/persistence.xml
Adds missing metadata for Hibernate Reactive. Without this, when there are entities with `@ManyToMany` or `@ElementCollection` then following error was being thrown:
```
Caused by: org.hibernate.MappingException: Could not find appropriate constructor for org.hibernate.reactive.persister.collection.impl.ReactiveBasicCollectionPersister
```
The test was already using mysql community docker so I have not added anything extra.
> Add missing metadata for Hibernate Reactive (needed for some collections mappings)

- metadata/org.eclipse.jetty/jetty-server/12.0.1/reflect-config.json
- tests/src/org.eclipse.jetty/jetty-server/12.0.1/src/test/java/jetty/JettyTests.java
Closes https://github.com/oracle/graalvm-reachability-metadata/issues/476
> Add reflection metadata for Jetty's ForwardedRequestCustomizer

- library-and-framework-list.json
Starting with 8.0.4 itext core includes reachability metadata into library.
> Add itext core libraries into library-and-framework-list.json

- tests/src/org.eclipse.jetty/jetty-client/11.0.12/src/test/java/org_eclipse_jetty/jetty_client/JettyClientTest.java
This tries to stabilize the flaky Jetty client test.
- Finds an ephemeral free port and uses this for docker
- uses docker publish in the form `127.0.0.1:<free port>:80`
- uses `127.0.0.1` instead of localhost
> Try to stabilize Jetty test

- metadata/org.thymeleaf/thymeleaf/3.1.0.M2/reflect-config.json
- metadata/org.thymeleaf/thymeleaf/3.1.0.RC1/reflect-config.json
- tests/src/org.thymeleaf/thymeleaf/3.1.0.M2/src/test/java/org/thymeleaf/ExpressionUtilsTest.java
- tests/src/org.thymeleaf/thymeleaf/3.1.0.M2/src/test/java/org/thymeleaf/ThymeleafTest.java
- tests/src/org.thymeleaf/thymeleaf/3.1.0.RC1/src/test/java/org/thymeleaf/ExpressionUtilsTest.java
- tests/src/org.thymeleaf/thymeleaf/3.1.0.RC1/src/test/java/org/thymeleaf/ThymeleafTest.java
To prevent Thymeleaf templates from accessing methods on built-in Java types that are not allowed, it ships with a list of allowed supertypes. Its `org.thymeleaf.util.ExpressionUtils` type has an `isMemberAllowed` method that calls `getDeclaredMethods()` on those types, so that needs to work for all these types in a native image. This PR ensures that.
Recent versions of Thymeleaf have expanded the list with two additional types, which is why the M2 version has 7 new entries while the RC1 / latest has 9. For details, check out
[the source code.](https://github.com/thymeleaf/thymeleaf/blob/3.1-master/lib/thymeleaf/src/main/java/org/thymeleaf/util/ExpressionUtils.java)
None.
> Allow Thymeleaf to check for allowed method access of Java supertypes

- metadata/org.apache.kafka/kafka-clients/3.5.1/reflect-config.json
- tests/src/org.apache.kafka/kafka-clients/3.5.1/build.gradle
- tests/src/org.apache.kafka/kafka-clients/3.5.1/src/test/java/org_apache_kafka/kafka_clients/KafkaClientsTest.java
Closes #510 
Add missing metadata for Kafka Client SCRAM/SASL mechanism.
Note: This is my first PR in this repo: any help in the code review is greatly appreciated!
(example link to code section)
> Add missing metadata for kafka client sasl scram mechanism

- metadata/org.hibernate.orm/hibernate-core/6.2.0.Final/reflect-config.json
- metadata/org.hibernate.orm/hibernate-core/6.5.0.Final/reflect-config.json
- tests/src/org.hibernate.orm/hibernate-core/6.5.0.Final/src/test/java/org_hibernate_orm/hibernate_core/IdentifierGeneratorTest.java
Add missing metadata for hibernate-core required to instantiate generator types retrieved from annotation attribute.
Closes: #323
> Add missing metadata for hibernate-core

- metadata/index.json
- metadata/org.apache.commons/commons-dbcp2/2.12.0/index.json
- metadata/org.apache.commons/commons-dbcp2/2.12.0/resource-config.json
- metadata/org.apache.commons/commons-dbcp2/index.json
- tests/src/index.json
- tests/src/org.apache.commons/commons-dbcp2/2.12.0/.gitignore
- tests/src/org.apache.commons/commons-dbcp2/2.12.0/build.gradle
- tests/src/org.apache.commons/commons-dbcp2/2.12.0/gradle.properties
- tests/src/org.apache.commons/commons-dbcp2/2.12.0/settings.gradle
- tests/src/org.apache.commons/commons-dbcp2/2.12.0/src/test/java/org_apache_commons/commons_dbcp2/CommonsDbcp2Test.java
Adds resource-config.json or else resource locales won't be loaded in GraalVM and an error is thrown: 
```
java.util.MissingResourceException: Can't find bundle for base name org.apache.commons.dbcp2.LocalStrings, locale en_US
```
Using H2 in memory database for the test.
> Added metadata resouce-config.json for org.apache.commons:commons-dbcp2:2.12.0

- metadata/com.itextpdf/forms/index.json
- metadata/com.itextpdf/io/index.json
- metadata/com.itextpdf/kernel/index.json
- metadata/com.itextpdf/layout/index.json
- metadata/com.itextpdf/svg/index.json
Starting from 8.0.4 itext core includes reachability metadata into library.
Looking at https://www.graalvm.org/native-image/libraries-and-frameworks/ it seems there is a redundancy in terms of supported versions of itext core libs. I believe removing 'latest' key from index.json should remove '8.0.3 - latest' range from the page above and leave only 8.0.3. Though I don't see any similar example in the whole repo so not sure.
> Remove 'latest' key from index.json for itext metadata

- library-and-framework-list-schema.json
That 2nd details entry in the example was confusing, because if the Native Image config is tracked in this repo vs upstream then that would be tracked in files such as https://github.com/oracle/graalvm-reachability-metadata/blob/master/metadata/io.netty/netty-common/index.json and not in https://github.com/oracle/graalvm-reachability-metadata/blob/master/library-and-framework-list.json which seems to only be when it is in upsteam.
> Remove confusing example in library-and-framework-list-schema.json

- metadata/com.github.luben/zstd-jni/1.5.2-5/resource-config.json
MacOS shared objects have `dylib` suffix, not `dylyb`
Fixes a bug
none
> Fix typo in the zstd-jni resource config

- metadata/org.testcontainers/testcontainers/1.19.8/index.json
- metadata/org.testcontainers/testcontainers/1.19.8/proxy-config.json
- metadata/org.testcontainers/testcontainers/1.19.8/reflect-config.json
- metadata/org.testcontainers/testcontainers/1.19.8/resource-config.json
- metadata/org.testcontainers/testcontainers/index.json
- tests/src/index.json
- tests/src/org.testcontainers/testcontainers/1.19.8/.gitignore
- tests/src/org.testcontainers/testcontainers/1.19.8/README.md
- tests/src/org.testcontainers/testcontainers/1.19.8/build.gradle
- tests/src/org.testcontainers/testcontainers/1.19.8/gradle.properties
- tests/src/org.testcontainers/testcontainers/1.19.8/required-docker-images.txt
- tests/src/org.testcontainers/testcontainers/1.19.8/settings.gradle
- tests/src/org.testcontainers/testcontainers/1.19.8/src/main/java/org_testcontainers/testcontainers/FindJsonSerialization.java
- tests/src/org.testcontainers/testcontainers/1.19.8/src/main/resources/DockerCommand-template.txt
- tests/src/org.testcontainers/testcontainers/1.19.8/src/main/resources/DockerObject-template.txt
- tests/src/org.testcontainers/testcontainers/1.19.8/src/test/java/org_testcontainers/testcontainers/TestcontainersTest.java
- tests/src/org.testcontainers/testcontainers/1.19.8/user-code-filter.json
Adds support for Testcontainers `1.19.8` and up, used by the current Spring Boot `3.3.x` line. Reuses #132 + #301 and upgrades the version.
Closes #492.
Tests are not enabled, same as current tests for Testcontainers `1.17.6` because it pulls a docker image with critical CVEs.
> Add metadata for testcontainers:1.19.8

- metadata/org.thymeleaf/thymeleaf/3.1.0.RC1/reflect-config.json
- tests/src/org.thymeleaf/thymeleaf/3.1.0.RC1/src/test/java/org/thymeleaf/ThymeleafTest.java
Add `org.thymeleaf.engine.IterationStatusVar` in Thymeleaf's reflect-config.json.
Ref. https://github.com/thymeleaf/thymeleaf/issues/987
- No I/O, just the added unit test.
> Add org.thymeleaf.engine.IterationStatusVar

- tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/tasks/CheckstyleInvocationTask.groovy
Makes sure that the Gradle Wrapper is used everywhere instead of the global Gradle installation.
> Use Gradle wrapper when invoking checkstyle

- .github/workflows/create-scheduled-release.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This PR introduces github workflow that creates automatic releases. The github action defined in workflow runs every two weeks.  
To make sure this PR works, we must have fixed `SNAPSHOT` version on master. Otherwise the process can't be fully automated and some steps may require manual maintainer inputs (since the master branch has protection rules that disallows direct committing onto it). With the fixed `SNAPSHOT` version on master, we are avoiding direct committing onto the protected master branch.
> Add GitHub Action for Scheduled Releases

- metadata/org.flywaydb/flyway-core/10.20.0/reflect-config.json
- tests/src/org.flywaydb/flyway-core/10.20.0/build.gradle
- tests/src/org.flywaydb/flyway-core/10.20.0/src/test/java/flyway/FlywayTests.java
This fixes the test which we use to generate the metadata for flyway. It also adds the entries found missing by @wilkinsona in https://github.com/oracle/graalvm-reachability-metadata/pull/556. This supersedes https://github.com/oracle/graalvm-reachability-metadata/pull/556.
> Fix tests for Flyway to generate correct reflection metadata

- tests/tck-build-logic/src/main/resources/allowed-docker-images/Dockerfile-testcontainers_ryuk
Add `testcontainers/ryuk:0.10.2` to allowed images list. No grype failures detected as of 2024-10-11:
```
$ grype testcontainers/ryuk:0.10.2
✔ Vulnerability DB                [updated]  
✔ Pulled image                    
✔ Loaded image                                                                                   testcontainers/ryuk:0.10.2
✔ Parsed image                                      sha256:61474639f5c88956870c4e99f4c00ba9f003ef0998fd31490fea9aebdc4f8679
✔ Cataloged contents                                       3930e92afc1cc6e6b7a91c973db3d63f9eccc2a713667c7d6fa7acf5a4bd1770
├── ✔ Packages                        [34 packages]  
├── ✔ File digests                    [230 files]  
├── ✔ File metadata                   [230 locations]  
└── ✔ Executables                     [20 …
```
> add testcontainers/ryuk:0.10.2 to allowed images list

- tests/src/org.testcontainers/testcontainers/1.17.6/required-docker-images.txt
- tests/src/org.testcontainers/testcontainers/1.17.6/src/test/java/org_testcontainers/testcontainers/TestcontainersTest.java
- tests/src/org.testcontainers/testcontainers/1.17.6/src/test/resources/META-INF/native-image/org/testcontainers/testcontainers/test/resource-config.json
- tests/src/org.testcontainers/testcontainers/1.17.6/src/test/resources/testcontainers.properties
- tests/src/org.testcontainers/testcontainers/1.19.8/required-docker-images.txt
- tests/src/org.testcontainers/testcontainers/1.19.8/src/test/java/org_testcontainers/testcontainers/TestcontainersTest.java
- tests/src/org.testcontainers/testcontainers/1.19.8/src/test/resources/META-INF/native-image/org/testcontainers/testcontainers/test/resource-config.json
- tests/src/org.testcontainers/testcontainers/1.19.8/src/test/resources/testcontainers.properties
Re-enable `Testcontainers` tests using the latest Ryuk image, `v0.10.2`, which does not package vulnerabilities - added it to the allow-list in #547 
There is one separate commit for each testcontainers version.
Closes #250 .
Both tests now access Docker; the `testcontainers/ryuk:0.10.2` image has been added to the list of required images.
Not applicable:
> Re-enable testcontainers tests

- .github/workflows/check-new-library-versions.yml
- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
- tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/tasks/GroupUnsupportedLibraries.groovy
It improves issue for unsupported libraries by grouping different versions of the same library.
Feature provided in this PR collects all comments from the issue that contains unsupported libraries (that jobs from workflows matrix added) and groups them by library name.
The final issue should look like this:
> Improve Library Versions Dependabot 

- .github/workflows/check-new-library-versions.yml
- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
- tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/tasks/GroupUnsupportedLibraries.groovy
Refactor implementation that collects unsupported library versions from parallel jobs in GitHub workflow
> Use Artifacts to Collect Unsupported Library Versions from Parallel Jobs

- library-and-framework-list.json
I recently added to one of my project the native metadata needed for GraalVM : 
<https://github.com/fugerit-org/fj-doc/tree/main/fj-doc-base>
<https://github.com/fugerit-org/fj-doc/tree/main/fj-doc-freemarker>
As for the "CONTRIBUTING" section, the metadata are mantained and tested direcly in my project repository, But as I understand a pull request is needed to be listed here <https://www.graalvm.org/native-image/libraries-and-frameworks/>
PS: This is my first pull request here, so I hope i filled it property. I tried to read the documentation and I hope I understood it properly.
PSS: Thanks a lot for your great work with GraalVM, we converted already a few production projects to AOT and we are very happy for the gain in 
Tests are note enabled as the metadata and testing is provided …
> Add native schema support for org.fugerit.java:fj-doc-base and org.fugeri.tjava:fj-doc-freemarker

- library-and-framework-list.json
This PR updates test and metadata locations for iText Core modules and adds iText pdfHtml to the list of tested libraries and frameworks.
> Update test and metadata locations for iText Core modules and iText add-ons

- metadata/org.eclipse.jetty/jetty-client/12.0.0.beta0/index.json
- metadata/org.eclipse.jetty/jetty-client/12.0.0.beta0/reflect-config.json
- metadata/org.eclipse.jetty/jetty-client/12.0.0.beta0/resource-config.json
- metadata/org.eclipse.jetty/jetty-client/index.json
- tests/src/index.json
- tests/src/org.eclipse.jetty/jetty-client/12.0.0.beta0/.gitignore
- tests/src/org.eclipse.jetty/jetty-client/12.0.0.beta0/build.gradle
- tests/src/org.eclipse.jetty/jetty-client/12.0.0.beta0/gradle.properties
- tests/src/org.eclipse.jetty/jetty-client/12.0.0.beta0/required-docker-images.txt
- tests/src/org.eclipse.jetty/jetty-client/12.0.0.beta0/settings.gradle
- tests/src/org.eclipse.jetty/jetty-client/12.0.0.beta0/src/test/java/org_eclipse_jetty/jetty_client/JettyClientTest.java
- tests/src/org.eclipse.jetty/jetty-client/12.0.0.beta0/user-code-filter.json
- Updated the version of 'org.eclipse.jetty:jetty-client' to 11.0.12 in the testImplementation scope and regenerated metadata.
> fix(jetty-client:12.0.0.beta0): resolve test failures

- metadata/org.apache.kafka/kafka-streams/3.5.1/reflect-config.json
Add the missing hints in Kafka Streams for org.apache.kafka.streams.errors.LogAndFailProcessingExceptionHandler
> Add Kafka Streams 3.9.0 missing hints

- metadata/org.apache.kafka/kafka-clients/3.5.1/resource-config.json
- tests/src/org.apache.kafka/kafka-clients/3.5.1/src/test/java/org_apache_kafka/kafka_clients/KafkaClientsTest.java
Adds missing kafka clients metadata and enables tests
> Added missing kafka clients metadata and enabled tests

- .github/CODEOWNERS
Add @matteoldani as a codeowner of allowed-doceker-images
> Update codeowners for allowed-doceker-images

- tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle
- tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/tasks/CleanInvocationTask.groovy
When running `./gradlew clean test -Pcoordinates=<maven-gav-coordinates>`, Gradle won't clean `build` directory made in a sub-project on the location specified with `-Pcoordinates`. At the moment user can't force clean sub-project build directory before running test.
In some cases Gradle may think that there are no changes since last run (for example if we just change environment variable) and therefore it won't build a new image. In this case, we would like to force a clean, before running the test.
This PR implements the fix for that.
**Note:** with this implementation, if we run `./gradlew clean` it will perform a clean on all sub-projects. Since `./gradlew test` runs all tests from all sub-projects, I would say that this is desirable behavior.
> Make clean task recognize test coordinates

- tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/DockerUtils.java
- tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/GrypeTask.java
- tests/tck-build-logic/src/main/java/org/graalvm/internal/tck/model/grype/GrypeEntry.java
Make vulnerabilities scanner less strict in order to accept slightly vulnerable images that are less vulnerable than the currently existing allowed images.
Fixes: https://github.com/oracle/graalvm-reachability-metadata/issues/540
> Make vulnerabilities scanner less strict
